In [2]:
import pandas as pd
from sqlalchemy import create_engine

In [3]:
rds_connection_string = "postgres:delphicitb969@localhost:5432/education_db"
engine = create_engine(f'postgresql://{rds_connection_string}')

In [10]:
csv_file = "education-statistics/EdStatsCountry.csv"
edstats_country_df = pd.read_csv(csv_file)
edstats_country_df

,Country Code,Short Name,Table Name,Long Name,2-alpha code,Currency Unit,Special Notes,Region,Income Group,WB-2 code,National accounts base year,National accounts reference year,SNA price valuation,Lending category,Other groups,System of National Accounts,Alternative conversion factor,PPP survey year,Balance of Payments Manual in use
0,ABW,Aruba,Aruba,Aruba,AW,Aruban florin,SNA data for 2000-2011 are updated from offici...,Latin America & Caribbean,High income: nonOECD,AW,2000,NaN,Value added at basic prices (VAB),NaN,NaN,Country uses the 1993 System of National Accou...,NaN,NaN,"IMF Balance of Payments Manual, 6th edition."
1,AFG,Afghanistan,Afghanistan,Islamic State of Afghanistan,AF,Afghan afghani,Fiscal year end: March 20; reporting period fo...,South Asia,Low income,AF,2002/03,NaN,Value added at basic prices (VAB),IDA,HIPC,Country uses the 1993 System of National Accou...,NaN,NaN,NaN
2,AGO,Angola,Angola,People's Republic of Angola,AO,Angolan kwanza,"April 2013 database update: Based on IMF data,...",Sub-Saharan Africa,Upper middle income,AO,2002,NaN,Value added at producer prices (VAP),IBRD,NaN,Country uses the 1993 System of National Accou...,1991–96,2005,"IMF Balance of Payments Manual, 6th edition."
3,ALB,Albania,Albania,Republic of Albania,AL,Albanian lek,NaN,Europe & Central Asia,Upper middle income,AL,Original chained constant price data are resca...,1996.0,Value added at basic prices (VAB),IBRD,NaN,Country uses the 1993 System of National Accou...,NaN,Rolling,"IMF Balance of Payments Manual, 6th edition."
4,AND,Andorra,Andorra,Principality of Andorra,AD,Euro,NaN,Europe & Central Asia,High income: nonOECD,AD,1990,NaN,NaN,NaN,NaN,Country uses the 1968 System of National Accou...,NaN,NaN,NaN
5,ARB,Arab World,Arab World,Arab World,1A,NaN,Arab World aggregate. Arab World is composed o...,NaN,NaN,1A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,ARE,United Arab Emirates,United Arab Emirates,United Arab Emirates,AE,U.A.E. dirham,April 2013 database update: Based on data from...,Middle East & North Africa,High income: nonOECD,AE,2007,NaN,Value added at producer prices (VAP),NaN,NaN,Country uses the 1993 System of National Accou...,NaN,NaN,"IMF Balance of Payments Manual, 6th edition."
7,ARG,Argentina,Argentina,Argentine Republic,AR,Argentine peso,NaN,Latin America & Caribbean,Upper middle income,AR,2004,NaN,Value added at basic prices (VAB),IBRD,NaN,Country uses the 1993 System of National Accou...,1971–84,2005,"IMF Balance of Payments Manual, 6th edition."
8,ARM,Armenia,Armenia,Republic of Armenia,AM,Armenian dram,NaN,Europe & Central Asia,Lower middle income,AM,Original chained constant price data are resca...,1996.0,Value added at basic prices (VAB),IBRD,NaN,Country uses the 1993 System of National Accou...,1990–95,2005,"IMF Balance of Payments Manual, 6th edition."
9,ASM,American Samoa,American Samoa,American Samoa,AS,U.S. dollar,NaN,East Asia & Pacific,Upper middle income,AS,NaN,NaN,NaN,NaN,NaN,Country uses the 1968 System of National Accou...,NaN,NaN,NaN
10,ATG,Antigua and Barbuda,Antigua and Barbuda,Antigua and Barbuda,AG,East Caribbean dollar,April 2012 database update: Based on official ...,Latin America & Caribbean,High income: nonOECD,AG,2006,NaN,Value added at basic prices (VAB),IBRD,NaN,Country uses the 1968 System of National Accou...,NaN,NaN,"IMF Balance of Payments Manual, 6th edition."
11,AUS,Australia,Australia,Commonwealth of Australia,AU,Australian dollar,Fiscal year end: June 30; reporting period for...,East Asia & Pacific,High income: OECD,AU,Original chained constant price data are resca...,2012.0,Value added at basic prices (VAB),NaN,NaN,Country uses the 2008 System of National Accou...,NaN,2011,"IMF Balance of Payments Manual, 6th edition."
12,AUT,Austria,Austria,Republic of Austria,AT,Euro,A simple multiplier is used to convert the nat...,Europe & Central Asia,High income: OECD,AT,2005,NaN,Value added at basic prices (VAB),NaN,Euro area,Country uses the 1993 System of National Accou...,NaN,Rolling,"IMF Balance of Payments Manual, 6th edition."
13,AZE,Azerbaijan,Azerbaijan,Republic of Azerbaijan,AZ,New Azeri manat,April 2012 database update: National accounts ...,Europe & Central Asia,Upper middle income,AZ,2000,NaN,Value added at basic prices (VAB),IBRD,NaN,Country uses the 1993 System of National Accou...,1992–95,2005,"IMF Balance of Payments Manual, 6th edition."
14,BDI,Burundi,Burundi,Republic of Burundi,BI,Burundi franc,NaN,Sub-Saharan Africa,Low income,BI,2005,NaN,Value added at basic prices (VAB),IDA,HIPC,Country uses the 1993 System of National Accou...,NaN,2005,"IMF Balance of Payments Manual, 6th edition."
15,BEL,Belgium,Belgium,Kingdom of Belgium,BE,Euro,A simple multiplier is used to convert the nat...,Europe & Central Asia,High income: OECD,BE,2005,NaN,Value added at basic prices (VAB),NaN,Euro area,Country uses the 1993 System of National Accou...,NaN,Rolling,"IMF Balance of Payments Manual, 6th edition."
16,BEN,Benin,Benin,Republic of Benin,BJ,CFA franc,NaN,Sub-Saharan Africa,Low income,BJ,1985,NaN,Value added at producer prices (VAP),IDA,HIPC,Country uses the 1968 System of National Accou...,1992,2005,"IMF Balance of Payments Manual, 6th edition."
17,BFA,Burkina Faso,Burkina Faso,Burkina Faso,BF,CFA franc,NaN,Sub-Saharan Africa,Low income,BF,1999,NaN,Value added at basic prices (VAB),IDA,HIPC,Country uses the 1993 System of National Accou...,1992–93,2005,"IMF Balance of Payments Manual, 6th edition."
18,BGD,Bangladesh,Bangladesh,People's Republic of Bangladesh,BD,Bangladeshi taka,Fiscal year end: June 30; reporting period for...,South Asia,Low income,BD,1995/96,NaN,Value added at basic prices (VAB),IDA,NaN,Country uses the 1993 System of National Accou...,NaN,2005,"IMF Balance of Payments Manual, 6th edition."
19,BGR,Bulgaria,Bulgaria,Republic of Bulgaria,BG,Bulgarian lev,April 2011 database update: The National Stati...,Europe & Central Asia,Upper middle income,BG,Original chained constant price data are resca...,2002.0,Value added at basic prices (VAB),IBRD,NaN,Country uses the 1993 System of National Accou...,"1978–89, 1991–92",Rolling,"IMF Balance of Payments Manual, 6th edition."
20,BHR,Bahrain,Bahrain,Kingdom of Bahrain,BH,Bahraini dinar,NaN,Middle East & North Africa,High income: nonOECD,BH,1985,NaN,Value added at producer prices (VAP),NaN,NaN,Country uses the 1968 System of National Accou...,NaN,2005,"IMF Balance of Payments Manual, 6th edition."
21,BHS,The Bahamas,"Bahamas, The",Commonwealth of The Bahamas,BS,Bahamian dollar,NaN,Latin America & Caribbean,High income: nonOECD,BS,2006,NaN,Value added at basic prices (VAB),NaN,NaN,Country uses the 1993 System of National Accou...,NaN,NaN,"IMF Balance of Payments Manual, 6th edition."
22,BIH,Bosnia and Herzegovina,Bosnia and Herzegovina,Bosnia and Herzegovina,BA,Bosnia and Herzegovina convertible mark,NaN,Europe & Central Asia,Upper middle income,BA,Original chained constant price data are resca...,1996.0,Value added at basic prices (VAB),IBRD,NaN,Country uses the 1993 System of National Accou...,NaN,Rolling,"IMF Balance of Payments Manual, 6th edition."
23,BLR,Belarus,Belarus,Republic of Belarus,BY,Belarusian rubel,NaN,Europe & Central Asia,Upper middle income,BY,Original chained constant price data are resca...,2000.0,Value added at basic prices (VAB),IBRD,NaN,Country uses the 1993 System of National Accou...,1990–95,2005,"IMF Balance of Payments Manual, 6th edition."
24,BLZ,Belize,Belize,Belize,BZ,Belize dollar,NaN,Latin America & Caribbean,Upper middle income,BZ,2000,NaN,Value added at basic prices (VAB),IBRD,NaN,Country uses the 1993 System of National Accou...,NaN,NaN,"IMF Balance of Payments Manual, 6th edition."
25,BMU,Bermuda,Bermuda,The Bermudas,BM,Bermuda dollar,NaN,North America,High income: nonOECD,BM,2006,NaN,Value added at basic prices (VAB),NaN,NaN,Country uses the 1993 System of National Accou...,NaN,NaN,"IMF Balance of Payments Manual, 6th edition."
26,BOL,Bolivia,Bolivia,Plurinational State of Bolivia,BO,Bolivian Boliviano,NaN,Latin America & Caribbean,Lower middle income,BO,1990,NaN,Value added at basic prices (VAB),Blend,HIPC,Country uses the 1968 System of National Accou...,1960–85,2005,"IMF Balance of Payments Manual, 6th edition."
27,BRA,Brazil,Brazil,Federative Republic of Brazil,BR,Brazilian real,NaN,Latin America & Caribbean,Upper middle income,BR,2000,NaN,Value added at basic prices (VAB),IBRD,NaN,Country uses the 1993 System of National Accou...,NaN,2005,"IMF Balance of Payments Manual, 6th edition."
28,BRB,Barbados,Barbados,Barbados,BB,Barbados dollar,NaN,Latin America & Caribbean,High income: nonOECD,BB,1974,NaN,Value added at basic prices (VAB),NaN,NaN,Country uses the 1968 System of National Accou...,NaN,NaN,"IMF Balance of Payments Manual, 6th edition."
29,BRN,Brunei,Brunei Darussalam,Brunei Darussalam,BN,Brunei dollar,NaN,East Asia & Pacific,High income: nonOECD,BN,2000,NaN,Value added at producer prices (VAP),NaN,NaN,Country uses the 1993 System of National Accou...,NaN,2005,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
211,TCD,Chad,Chad,Republic of Chad,TD,CFA franc,"Based on IMF data, national accounts data have...",Sub-Saharan Africa,Low income,TD,2005,NaN,Value added at basic prices (VAB),IDA,HIPC,Country uses the 1993 System of National Accou...,NaN,2005,"IMF Balance of Payments Manual, 6th edition."
212,TGO,Togo,Togo,Republic of Togo,TG,CFA franc,"April 2013 database update: Based on IMF data,...",Sub-Saharan Africa,Low income,TG,2000,NaN,Value added at producer prices (VAP),IDA,HIPC,Country uses the 1968 System of National Accou...,NaN,2005,"IMF Balance of Payments Manual, 6th edition."
213,THA,Thailand,Thailand,Kingdom of Thailand,TH,Thai baht,Fiscal year end: September 30; reporting perio...,East Asia & Pacific,Upper middle income,TH,1988,NaN,Value added at producer prices (VAP),IBRD,NaN,Country uses the 1993 System of National Accou...,NaN,2005,"IMF Balance of Payments Manual, 6th edition."
214,TJK,Tajikistan,Tajikistan,Republic of Tajikistan,TJ,Tajik somoni,NaN,Europe & Central Asia,Low income,TJ,Original chained constant price data are resca...,2000.0,Value added at basic prices (VAB),IDA,NaN,Country uses the 1993 System of National Accou...,1990–95,2005,"IMF Balance of Payments Manual, 6th edition."
215,TKM,Turkmenistan,Turkmenistan,Turkmenistan,TM,New Turkmen manat,"On January 1, 2009, the Turkmen manat was rede...",Europe & Central Asia,Upper middle income,TM,2005,NaN,Value added at basic prices (VAB),IBRD,NaN,Country uses the 1993 System of National Accou...,"1987–95, 1997–2007",NaN,"IMF Balance of Payments Manual, 6th edition."
216,TLS,Timor-Leste,Timor-Leste,Democratic Republic of Timor-Leste,TL,U.S. dollar,"Based on official government statistics, natio...",East Asia & Pacific,Lower middle income,TP,2010,NaN,Value added at basic prices (VAB),Blend,NaN,Country uses the 2008 System of National Accou...,NaN,NaN,NaN
217,TON,Tonga,Tonga,Kingdom of Tonga,TO,Tongan pa'anga,Fiscal year ends on June 30; reporting period ...,East Asia & Pacific,Upper middle income,TO,2010/11,NaN,Value added at basic prices (VAB),IDA,NaN,Country uses the 1993 System of National Accou...,NaN,NaN,"IMF Balance of Payments Manual, 6th edition."
218,TTO,Trinidad and Tobago,Trinidad and Tobago,Republic of Trinidad and Tobago,TT,Trinidad and Tobago dollar,NaN,Latin America & Caribbean,High income: nonOECD,TT,2000,NaN,Value added at basic prices (VAB),IBRD,NaN,Country uses the 1993 System of National Accou...,NaN,NaN,"IMF Balance of Payments Manual, 6th edition."
219,TUN,Tunisia,Tunisia,Republic of Tunisia,TN,Tunisian dinar,National accounts data from 2005 onward have b...,Middle East & North Africa,Upper middle income,TN,2005,NaN,Value added at basic prices (VAB),IBRD,NaN,Country uses the 1993 System of National Accou...,NaN,2005,"IMF Balance of Payments Manual, 6th edition."
220,TUR,Turkey,Turkey,Republic of Turkey,TR,New Turkish lira,NaN,Europe & Central Asia,Upper middle income,TR,1998,NaN,Value added at basic prices (VAB),IBRD,NaN,Country uses the 1993 System of National Accou...,NaN,Rolling,"IMF Balance of Payments Manual, 6th edition."
221,TUV,Tuvalu,Tuvalu,Tuvalu,TV,Australian dollar,"Based on data from the IMF, World Bank and gov...",East Asia & Pacific,Upper middle income,TV,2005,NaN,Value added at basic prices (VAB),IDA,NaN,Country uses the 1968 System of National Accou...,NaN,NaN,NaN
222,TZA,Tanzania,Tanzania,United Republic of Tanzania,TZ,Tanzanian shilling,NaN,Sub-Saharan Africa,Low income,TZ,Original chained constant price data are resca...,2001.0,Value added at basic prices (VAB),IDA,HIPC,Country uses the 1993 System of National Accou...,NaN,2005,"IMF Balance of Payments Manual, 6th edition."
223,UGA,Uganda,Uganda,Republic of Uganda,UG,Ugandan shilling,Fiscal year end: June 30; reporting period for...,Sub-Saharan Africa,Low income,UG,2001/02,NaN,Value added at basic prices (VAB),IDA,HIPC,Country uses the 1968 System of National Accou...,NaN,2005,"IMF Balance of Payments Manual, 6th edition."
224,UKR,Ukraine,Ukraine,Ukraine,UA,Ukrainian hryvnia,NaN,Europe & Central Asia,Lower middle income,UA,Original chained constant price data are resca...,2003.0,Value added at basic prices (VAB),IBRD,NaN,Country uses the 1993 System of National Accou...,1987–95,2005,"IMF Balance of Payments Manual, 6th edition."
225,UMC,Upper middle income,Upper middle income,Upper middle income,XT,NaN,Upper middle income group aggregate. Upper-mid...,NaN,NaN,XT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
226,URY,Uruguay,Uruguay,Oriental Republic of Uruguay,UY,Uruguayan peso,"In 2011, the Central Bank revised national acc...",Latin America & Caribbean,High income: nonOECD,UY,2005,NaN,Value added at basic prices (VAB),IBRD,NaN,Country uses the 1993 System of National Accou...,NaN,2005,"IMF Balance of Payments Manual, 6th edition."
227,USA,United States,United States,United States of America,US,U.S. dollar,Fiscal year end: September 30; reporting perio...,North America,High income: OECD,US,Original chained constant price data are resca...,2005.0,Value added at basic prices (VAB),NaN,NaN,Country uses the 2008 System of National Accou...,NaN,2011,"IMF Balance of Payments Manual, 6th edition."
228,UZB,Uzbekistan,Uzbekistan,Republic of Uzbekistan,UZ,Uzbek sum,NaN,Europe & Central Asia,Lower middle income,UZ,Original chained constant price data are resca...,1997.0,Value added at basic prices (VAB),Blend,NaN,Country uses the 1993 System of National Accou...,1990–95,NaN,"IMF Balance of Payments Manual, 6th edition."
229,VCT,St. Vincent and the Grenadines,St. Vincent and the Grenadines,St. Vincent and the Grenadines,VC,East Caribbean dollar,April 2012 database update: Based on official ...,Latin America & Caribbean,Upper middle income,VC,2006,NaN,Value added at basic prices (VAB),Blend,NaN,Country uses the 1993 System of National Accou...,NaN,NaN,"IMF Balance of Payments Manual, 6th edition."
230,VEN,Venezuela,"Venezuela, RB",República Bolivariana de Venezuela,VE,Venezuelan bolivar fuerte,NaN,Latin America & Caribbean,Upper middle income,VE,1997,NaN,Value added at basic prices (VAB),IBRD,NaN,Country uses the 1993 System of National Accou...,NaN,2005,"IMF Balance of Payments Manual, 6th edition."
231,VIR,Virgin Islands,Virgin Islands (U.S.),Virgin Islands of the United States,VI,U.S. dollar,NaN,Latin America & Caribbean,High income: nonOECD,VI,1982,NaN,NaN,NaN,NaN,Country uses the 1968 System of National Accou...,NaN,NaN,NaN
232,VNM,Vietnam,Vietnam,Socialist Republic of Vietnam,VN,Vietnamese dong,Based on data from the Vietnam Statistics Offi...,East Asia & Pacific,Lower middle income,VN,2010,NaN,Value added at producer prices (VAP),Blend,NaN,Country uses the 1993 System of National Accou...,1991,2005,"IMF Balance of Payments Manual, 6th edition."
233,VUT,Vanuatu,Vanuatu,Republic of Vanuatu,VU,Vanuatu vatu,"Based on official government statistics, value...",East Asia & Pacific,Lower middle income,VU,2006,NaN,Value added at basic prices (VAB),IDA,NaN,Country uses the 1993 System of National Accou...,NaN,NaN,"IMF Balance of Payments Manual, 6th edition."
234,WLD,World,World,World,1W,NaN,World aggregate.,NaN,NaN,1W,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
235,WSM,Samoa,Samoa,Samoa,WS,Samoan tala,Fiscal year ends on June 30; reporting period ...,East Asia & Pacific,Lower middle income,WS,2002,NaN,Value added at basic prices (VAB),IDA,NaN,Country uses the 1993 System of National Accou...,NaN,NaN,"IMF Balance of Payments Manual, 6th edition."
236,XKX,Kosovo,Kosovo,Republic of Kosovo,NaN,Euro,"Kosovo became a World Bank member on June 29, ...",Europe & Central Asia,Lower middle income,KV,2008,NaN,Value added at basic prices (VAB),IDA,NaN,Country uses the 1993 System of National Accou...,NaN,NaN,NaN
237,YEM,Yemen,"Yemen, Rep.",Republic of Yemen,YE,Yemeni rial,Based on official government statistics and In...,Middle East & North Africa,Lower middle income,RY,2007,NaN,Value added at producer prices (VAP),IDA,NaN,Country uses the 1993 System of National Accou...,1990–96,2005,"IMF Balance of Payments Manual, 6th edition."
238,ZAF,South Africa,South Africa,Republic of South Africa,ZA,South African rand,Fiscal year end: March 31; reporting period fo...,Sub-Saharan Africa,Upper middle income,ZA,2005,NaN,Value added at basic prices (VAB),IBRD,NaN,Country uses the 1993 System of National Accou...,NaN,2005,"IMF Balance of Payments Manual, 6th edition."
239,ZMB,Zambia,Zambia,Republic of Zambia,ZM,New Zambian kwacha,National accounts data have rebased to reflect...,Sub-Saharan Africa,Lower middle income,ZM,1994,NaN,Value added at basic prices (VAB),IDA,HIPC,Country uses the 1968 System of National Accou...,1990–92,2005,"IMF Balance of Payments Manual, 6th edition."
240,ZWE,Zimbabwe,Zimbabwe,Republic of Zimbabwe,ZW,U.S. dollar,Fiscal year end: June 30; reporting period for...,Sub-Saharan Africa,Low income,ZW,2009,NaN,Value added at basic prices (VAB),Blend,NaN,Country uses the 1993 System of National Accou...,"1991, 1998",2005,"IMF Balance of Payments Manual, 6th edition."

In [11]:
edstats_country = edstats_country_df[['Country Code', 'Short Name', 'Table Name', 'Long Name', '2-alpha code', 'Currency Unit', 'Region', 'Income Group']].copy()
edstats_country

,Country Code,Short Name,Table Name,Long Name,2-alpha code,Currency Unit,Region,Income Group
0,ABW,Aruba,Aruba,Aruba,AW,Aruban florin,Latin America & Caribbean,High income: nonOECD
1,AFG,Afghanistan,Afghanistan,Islamic State of Afghanistan,AF,Afghan afghani,South Asia,Low income
2,AGO,Angola,Angola,People's Republic of Angola,AO,Angolan kwanza,Sub-Saharan Africa,Upper middle income
3,ALB,Albania,Albania,Republic of Albania,AL,Albanian lek,Europe & Central Asia,Upper middle income
4,AND,Andorra,Andorra,Principality of Andorra,AD,Euro,Europe & Central Asia,High income: nonOECD
5,ARB,Arab World,Arab World,Arab World,1A,NaN,NaN,NaN
6,ARE,United Arab Emirates,United Arab Emirates,United Arab Emirates,AE,U.A.E. dirham,Middle East & North Africa,High income: nonOECD
7,ARG,Argentina,Argentina,Argentine Republic,AR,Argentine peso,Latin America & Caribbean,Upper middle income
8,ARM,Armenia,Armenia,Republic of Armenia,AM,Armenian dram,Europe & Central Asia,Lower middle income
9,ASM,American Samoa,American Samoa,American Samoa,AS,U.S. dollar,East Asia & Pacific,Upper middle income
10,ATG,Antigua and Barbuda,Antigua and Barbuda,Antigua and Barbuda,AG,East Caribbean dollar,Latin America & Caribbean,High income: nonOECD
11,AUS,Australia,Australia,Commonwealth of Australia,AU,Australian dollar,East Asia & Pacific,High income: OECD
12,AUT,Austria,Austria,Republic of Austria,AT,Euro,Europe & Central Asia,High income: OECD
13,AZE,Azerbaijan,Azerbaijan,Republic of Azerbaijan,AZ,New Azeri manat,Europe & Central Asia,Upper middle income
14,BDI,Burundi,Burundi,Republic of Burundi,BI,Burundi franc,Sub-Saharan Africa,Low income
15,BEL,Belgium,Belgium,Kingdom of Belgium,BE,Euro,Europe & Central Asia,High income: OECD
16,BEN,Benin,Benin,Republic of Benin,BJ,CFA franc,Sub-Saharan Africa,Low income
17,BFA,Burkina Faso,Burkina Faso,Burkina Faso,BF,CFA franc,Sub-Saharan Africa,Low income
18,BGD,Bangladesh,Bangladesh,People's Republic of Bangladesh,BD,Bangladeshi taka,South Asia,Low income
19,BGR,Bulgaria,Bulgaria,Republic of Bulgaria,BG,Bulgarian lev,Europe & Central Asia,Upper middle income
20,BHR,Bahrain,Bahrain,Kingdom of Bahrain,BH,Bahraini dinar,Middle East & North Africa,High income: nonOECD
21,BHS,The Bahamas,"Bahamas, The",Commonwealth of The Bahamas,BS,Bahamian dollar,Latin America & Caribbean,High income: nonOECD
22,BIH,Bosnia and Herzegovina,Bosnia and Herzegovina,Bosnia and Herzegovina,BA,Bosnia and Herzegovina convertible mark,Europe & Central Asia,Upper middle income
23,BLR,Belarus,Belarus,Republic of Belarus,BY,Belarusian rubel,Europe & Central Asia,Upper middle income
24,BLZ,Belize,Belize,Belize,BZ,Belize dollar,Latin America & Caribbean,Upper middle income
25,BMU,Bermuda,Bermuda,The Bermudas,BM,Bermuda dollar,North America,High income: nonOECD
26,BOL,Bolivia,Bolivia,Plurinational State of Bolivia,BO,Bolivian Boliviano,Latin America & Caribbean,Lower middle income
27,BRA,Brazil,Brazil,Federative Republic of Brazil,BR,Brazilian real,Latin America & Caribbean,Upper middle income
28,BRB,Barbados,Barbados,Barbados,BB,Barbados dollar,Latin America & Caribbean,High income: nonOECD
29,BRN,Brunei,Brunei Darussalam,Brunei Darussalam,BN,Brunei dollar,East Asia & Pacific,High income: nonOECD
...,...,...,...,...,...,...,...,...
211,TCD,Chad,Chad,Republic of Chad,TD,CFA franc,Sub-Saharan Africa,Low income
212,TGO,Togo,Togo,Republic of Togo,TG,CFA franc,Sub-Saharan Africa,Low income
213,THA,Thailand,Thailand,Kingdom of Thailand,TH,Thai baht,East Asia & Pacific,Upper middle income
214,TJK,Tajikistan,Tajikistan,Republic of Tajikistan,TJ,Tajik somoni,Europe & Central Asia,Low income
215,TKM,Turkmenistan,Turkmenistan,Turkmenistan,TM,New Turkmen manat,Europe & Central Asia,Upper middle income
216,TLS,Timor-Leste,Timor-Leste,Democratic Republic of Timor-Leste,TL,U.S. dollar,East Asia & Pacific,Lower middle income
217,TON,Tonga,Tonga,Kingdom of Tonga,TO,Tongan pa'anga,East Asia & Pacific,Upper middle income
218,TTO,Trinidad and Tobago,Trinidad and Tobago,Republic of Trinidad and Tobago,TT,Trinidad and Tobago dollar,Latin America & Caribbean,High income: nonOECD
219,TUN,Tunisia,Tunisia,Republic of Tunisia,TN,Tunisian dinar,Middle East & North Africa,Upper middle income
220,TUR,Turkey,Turkey,Republic of Turkey,TR,New Turkish lira,Europe & Central Asia,Upper middle income
221,TUV,Tuvalu,Tuvalu,Tuvalu,TV,Australian dollar,East Asia & Pacific,Upper middle income
222,TZA,Tanzania,Tanzania,United Republic of Tanzania,TZ,Tanzanian shilling,Sub-Saharan Africa,Low income
223,UGA,Uganda,Uganda,Republic of Uganda,UG,Ugandan shilling,Sub-Saharan Africa,Low income
224,UKR,Ukraine,Ukraine,Ukraine,UA,Ukrainian hryvnia,Europe & Central Asia,Lower middle income
225,UMC,Upper middle income,Upper middle income,Upper middle income,XT,NaN,NaN,NaN
226,URY,Uruguay,Uruguay,Oriental Republic of Uruguay,UY,Uruguayan peso,Latin America & Caribbean,High income: nonOECD
227,USA,United States,United States,United States of America,US,U.S. dollar,North America,High income: OECD
228,UZB,Uzbekistan,Uzbekistan,Republic of Uzbekistan,UZ,Uzbek sum,Europe & Central Asia,Lower middle income
229,VCT,St. Vincent and the Grenadines,St. Vincent and the Grenadines,St. Vincent and the Grenadines,VC,East Caribbean dollar,Latin America & Caribbean,Upper middle income
230,VEN,Venezuela,"Venezuela, RB",República Bolivariana de Venezuela,VE,Venezuelan bolivar fuerte,Latin America & Caribbean,Upper middle income
231,VIR,Virgin Islands,Virgin Islands (U.S.),Virgin Islands of the United States,VI,U.S. dollar,Latin America & Caribbean,High income: nonOECD
232,VNM,Vietnam,Vietnam,Socialist Republic of Vietnam,VN,Vietnamese dong,East Asia & Pacific,Lower middle income
233,VUT,Vanuatu,Vanuatu,Republic of Vanuatu,VU,Vanuatu vatu,East Asia & Pacific,Lower middle income
234,WLD,World,World,World,1W,NaN,NaN,NaN
235,WSM,Samoa,Samoa,Samoa,WS,Samoan tala,East Asia & Pacific,Lower middle income
236,XKX,Kosovo,Kosovo,Republic of Kosovo,NaN,Euro,Europe & Central Asia,Lower middle income
237,YEM,Yemen,"Yemen, Rep.",Republic of Yemen,YE,Yemeni rial,Middle East & North Africa,Lower middle income
238,ZAF,South Africa,South Africa,Republic of South Africa,ZA,South African rand,Sub-Saharan Africa,Upper middle income
239,ZMB,Zambia,Zambia,Republic of Zambia,ZM,New Zambian kwacha,Sub-Saharan Africa,Lower middle income
240,ZWE,Zimbabwe,Zimbabwe,Republic of Zimbabwe,ZW,U.S. dollar,Sub-Saharan Africa,Low income

In [12]:
edstats_country = edstats_country.rename(columns={"Country Code": "country_code",
                                                  "Short Name": "short_name",
                                                  "Table Name": "proper_name",
                                                  "Long Name":"long_name",
                                                  "2-alpha code": "two_alpha_code",
                                                  "Currency Unit": "currency_unit",
                                                  "Region": "region",
                                                  "Income Group": "income_group",})
edstats_country

,country_code,short_name,proper_name,long_name,two_alpha_code,currency_unit,region,income_group
0,ABW,Aruba,Aruba,Aruba,AW,Aruban florin,Latin America & Caribbean,High income: nonOECD
1,AFG,Afghanistan,Afghanistan,Islamic State of Afghanistan,AF,Afghan afghani,South Asia,Low income
2,AGO,Angola,Angola,People's Republic of Angola,AO,Angolan kwanza,Sub-Saharan Africa,Upper middle income
3,ALB,Albania,Albania,Republic of Albania,AL,Albanian lek,Europe & Central Asia,Upper middle income
4,AND,Andorra,Andorra,Principality of Andorra,AD,Euro,Europe & Central Asia,High income: nonOECD
5,ARB,Arab World,Arab World,Arab World,1A,NaN,NaN,NaN
6,ARE,United Arab Emirates,United Arab Emirates,United Arab Emirates,AE,U.A.E. dirham,Middle East & North Africa,High income: nonOECD
7,ARG,Argentina,Argentina,Argentine Republic,AR,Argentine peso,Latin America & Caribbean,Upper middle income
8,ARM,Armenia,Armenia,Republic of Armenia,AM,Armenian dram,Europe & Central Asia,Lower middle income
9,ASM,American Samoa,American Samoa,American Samoa,AS,U.S. dollar,East Asia & Pacific,Upper middle income
10,ATG,Antigua and Barbuda,Antigua and Barbuda,Antigua and Barbuda,AG,East Caribbean dollar,Latin America & Caribbean,High income: nonOECD
11,AUS,Australia,Australia,Commonwealth of Australia,AU,Australian dollar,East Asia & Pacific,High income: OECD
12,AUT,Austria,Austria,Republic of Austria,AT,Euro,Europe & Central Asia,High income: OECD
13,AZE,Azerbaijan,Azerbaijan,Republic of Azerbaijan,AZ,New Azeri manat,Europe & Central Asia,Upper middle income
14,BDI,Burundi,Burundi,Republic of Burundi,BI,Burundi franc,Sub-Saharan Africa,Low income
15,BEL,Belgium,Belgium,Kingdom of Belgium,BE,Euro,Europe & Central Asia,High income: OECD
16,BEN,Benin,Benin,Republic of Benin,BJ,CFA franc,Sub-Saharan Africa,Low income
17,BFA,Burkina Faso,Burkina Faso,Burkina Faso,BF,CFA franc,Sub-Saharan Africa,Low income
18,BGD,Bangladesh,Bangladesh,People's Republic of Bangladesh,BD,Bangladeshi taka,South Asia,Low income
19,BGR,Bulgaria,Bulgaria,Republic of Bulgaria,BG,Bulgarian lev,Europe & Central Asia,Upper middle income
20,BHR,Bahrain,Bahrain,Kingdom of Bahrain,BH,Bahraini dinar,Middle East & North Africa,High income: nonOECD
21,BHS,The Bahamas,"Bahamas, The",Commonwealth of The Bahamas,BS,Bahamian dollar,Latin America & Caribbean,High income: nonOECD
22,BIH,Bosnia and Herzegovina,Bosnia and Herzegovina,Bosnia and Herzegovina,BA,Bosnia and Herzegovina convertible mark,Europe & Central Asia,Upper middle income
23,BLR,Belarus,Belarus,Republic of Belarus,BY,Belarusian rubel,Europe & Central Asia,Upper middle income
24,BLZ,Belize,Belize,Belize,BZ,Belize dollar,Latin America & Caribbean,Upper middle income
25,BMU,Bermuda,Bermuda,The Bermudas,BM,Bermuda dollar,North America,High income: nonOECD
26,BOL,Bolivia,Bolivia,Plurinational State of Bolivia,BO,Bolivian Boliviano,Latin America & Caribbean,Lower middle income
27,BRA,Brazil,Brazil,Federative Republic of Brazil,BR,Brazilian real,Latin America & Caribbean,Upper middle income
28,BRB,Barbados,Barbados,Barbados,BB,Barbados dollar,Latin America & Caribbean,High income: nonOECD
29,BRN,Brunei,Brunei Darussalam,Brunei Darussalam,BN,Brunei dollar,East Asia & Pacific,High income: nonOECD
...,...,...,...,...,...,...,...,...
211,TCD,Chad,Chad,Republic of Chad,TD,CFA franc,Sub-Saharan Africa,Low income
212,TGO,Togo,Togo,Republic of Togo,TG,CFA franc,Sub-Saharan Africa,Low income
213,THA,Thailand,Thailand,Kingdom of Thailand,TH,Thai baht,East Asia & Pacific,Upper middle income
214,TJK,Tajikistan,Tajikistan,Republic of Tajikistan,TJ,Tajik somoni,Europe & Central Asia,Low income
215,TKM,Turkmenistan,Turkmenistan,Turkmenistan,TM,New Turkmen manat,Europe & Central Asia,Upper middle income
216,TLS,Timor-Leste,Timor-Leste,Democratic Republic of Timor-Leste,TL,U.S. dollar,East Asia & Pacific,Lower middle income
217,TON,Tonga,Tonga,Kingdom of Tonga,TO,Tongan pa'anga,East Asia & Pacific,Upper middle income
218,TTO,Trinidad and Tobago,Trinidad and Tobago,Republic of Trinidad and Tobago,TT,Trinidad and Tobago dollar,Latin America & Caribbean,High income: nonOECD
219,TUN,Tunisia,Tunisia,Republic of Tunisia,TN,Tunisian dinar,Middle East & North Africa,Upper middle income
220,TUR,Turkey,Turkey,Republic of Turkey,TR,New Turkish lira,Europe & Central Asia,Upper middle income
221,TUV,Tuvalu,Tuvalu,Tuvalu,TV,Australian dollar,East Asia & Pacific,Upper middle income
222,TZA,Tanzania,Tanzania,United Republic of Tanzania,TZ,Tanzanian shilling,Sub-Saharan Africa,Low income
223,UGA,Uganda,Uganda,Republic of Uganda,UG,Ugandan shilling,Sub-Saharan Africa,Low income
224,UKR,Ukraine,Ukraine,Ukraine,UA,Ukrainian hryvnia,Europe & Central Asia,Lower middle income
225,UMC,Upper middle income,Upper middle income,Upper middle income,XT,NaN,NaN,NaN
226,URY,Uruguay,Uruguay,Oriental Republic of Uruguay,UY,Uruguayan peso,Latin America & Caribbean,High income: nonOECD
227,USA,United States,United States,United States of America,US,U.S. dollar,North America,High income: OECD
228,UZB,Uzbekistan,Uzbekistan,Republic of Uzbekistan,UZ,Uzbek sum,Europe & Central Asia,Lower middle income
229,VCT,St. Vincent and the Grenadines,St. Vincent and the Grenadines,St. Vincent and the Grenadines,VC,East Caribbean dollar,Latin America & Caribbean,Upper middle income
230,VEN,Venezuela,"Venezuela, RB",República Bolivariana de Venezuela,VE,Venezuelan bolivar fuerte,Latin America & Caribbean,Upper middle income
231,VIR,Virgin Islands,Virgin Islands (U.S.),Virgin Islands of the United States,VI,U.S. dollar,Latin America & Caribbean,High income: nonOECD
232,VNM,Vietnam,Vietnam,Socialist Republic of Vietnam,VN,Vietnamese dong,East Asia & Pacific,Lower middle income
233,VUT,Vanuatu,Vanuatu,Republic of Vanuatu,VU,Vanuatu vatu,East Asia & Pacific,Lower middle income
234,WLD,World,World,World,1W,NaN,NaN,NaN
235,WSM,Samoa,Samoa,Samoa,WS,Samoan tala,East Asia & Pacific,Lower middle income
236,XKX,Kosovo,Kosovo,Republic of Kosovo,NaN,Euro,Europe & Central Asia,Lower middle income
237,YEM,Yemen,"Yemen, Rep.",Republic of Yemen,YE,Yemeni rial,Middle East & North Africa,Lower middle income
238,ZAF,South Africa,South Africa,Republic of South Africa,ZA,South African rand,Sub-Saharan Africa,Upper middle income
239,ZMB,Zambia,Zambia,Republic of Zambia,ZM,New Zambian kwacha,Sub-Saharan Africa,Lower middle income
240,ZWE,Zimbabwe,Zimbabwe,Republic of Zimbabwe,ZW,U.S. dollar,Sub-Saharan Africa,Low income

In [13]:
csv_file = "education-statistics/EdStatsCountry-Series.csv"
edstats_country_series_df = pd.read_csv(csv_file)
edstats_country_series_df

,ID Unique,CountryCode,SeriesCode,DESCRIPTION
0,1,ABW,SP.POP.TOTL,Data sources : United Nations World Population...
1,2,ABW,SP.POP.GROW,Data sources: United Nations World Population ...
2,3,AFG,SP.POP.GROW,Data sources: United Nations World Population ...
3,4,AFG,NY.GDP.PCAP.PP.CD,Estimates are based on regression.
4,5,AFG,SP.POP.TOTL,Data sources : United Nations World Population...
5,6,AFG,NY.GDP.MKTP.PP.KD,Estimates are based on regression.
6,7,AFG,NY.GNP.MKTP.PP.CD,Estimates are based on regression.
7,8,AFG,NY.GDP.MKTP.PP.CD,Estimates are based on regression.
8,9,AFG,NY.GDP.PCAP.PP.KD,Estimates are based on regression.
9,10,AFG,NY.GNP.PCAP.PP.CD,Estimates are based on regression.
10,11,AGO,SP.POP.TOTL,Data sources : United Nations World Population...
11,12,AGO,SP.POP.GROW,Data sources: United Nations World Population ...
12,13,ALB,SP.POP.GROW,Data sources: United Nations World Population ...
13,14,ALB,SP.POP.TOTL,"Data sources : Institute of Statistics, Eurostat"
14,15,AND,SP.POP.TOTL,Data sources : United Nations World Population...
15,16,AND,SP.POP.GROW,Data sources: United Nations World Population ...
16,17,ARE,SP.POP.GROW,Data sources: United Nations World Population ...
17,18,ARE,SP.POP.TOTL,Data sources : United Nations World Population...
18,19,ARG,NY.GDP.MKTP.PP.KD,Estimates are based on regression.
19,20,ARG,NY.GNP.MKTP.PP.CD,Estimates are based on regression.
20,21,ARG,NY.GDP.PCAP.PP.CD,Estimates are based on regression.
21,22,ARG,SP.POP.TOTL,Data sources : United Nations World Population...
22,23,ARG,NY.GNP.PCAP.PP.CD,Estimates are based on regression.
23,24,ARG,NY.GDP.PCAP.PP.KD,Estimates are based on regression.
24,25,ARG,SP.POP.GROW,Data sources: United Nations World Population ...
25,26,ARG,NY.GDP.MKTP.PP.CD,Estimates are based on regression.
26,27,ARM,SP.POP.GROW,Data sources: United Nations World Population ...
27,28,ARM,SP.POP.TOTL,Data sources : United Nations World Population...
28,29,ASM,SP.POP.TOTL,Data sources : United Nations World Population...
29,30,ASM,SP.POP.GROW,Data sources: United Nations World Population ...
...,...,...,...,...
583,584,UZB,NY.GDP.MKTP.PP.CD,Estimates are based on regression.
584,585,VCT,SP.POP.TOTL,Data sources : United Nations World Population...
585,586,VCT,SP.POP.GROW,Data sources: United Nations World Population ...
586,587,VEN,SP.POP.GROW,Data sources: United Nations World Population ...
587,588,VEN,SP.POP.TOTL,Data sources : United Nations World Population...
588,589,VEN,NY.GNP.PCAP.CD,Based on official exchange rates.
589,590,VIR,SP.POP.TOTL,"Data sources : U.S. Census Bureau, United Nati..."
590,591,VIR,SP.POP.GROW,"Data sources: U.S. Census Bureau, United Natio..."
591,592,VNM,SP.POP.GROW,Data sources: General Statistics Office of Vie...
592,593,VNM,SP.POP.TOTL,Data sources : General Statistics Office of Vi...
593,594,VUT,SP.POP.TOTL,Data sources : United Nations World Population...
594,595,VUT,SP.POP.GROW,Data sources: United Nations World Population ...
595,596,WSM,SP.POP.GROW,Data sources: United Nations World Population ...
596,597,WSM,SP.POP.TOTL,Data sources : United Nations World Population...
597,598,XKX,SP.POP.TOTL,Data sources : World Bank's Kosovo coutnry off...
598,599,XKX,NY.GDP.MKTP.PP.KD,Estimates are based on regression.
599,600,XKX,NY.GNP.MKTP.PP.CD,Estimates are based on regression.
600,601,XKX,SP.POP.GROW,Data sources: World Bank's Kosovo coutnry offi...
601,602,XKX,NY.GDP.PCAP.PP.CD,Estimates are based on regression.
602,603,XKX,NY.GNP.PCAP.PP.CD,Estimates are based on regression.
603,604,XKX,NY.GDP.MKTP.PP.CD,Estimates are based on regression.
604,605,XKX,NY.GDP.PCAP.PP.KD,Estimates are based on regression.
605,606,YEM,SP.POP.GROW,Data sources: United Nations World Population ...
606,607,YEM,SP.POP.TOTL,Data sources : United Nations World Population...
607,608,ZAF,SP.POP.TOTL,"Data sources : Statistics South Africa, United..."
608,609,ZAF,SP.POP.GROW,"Data sources : Statistics South Africa, United..."
609,610,ZMB,SP.POP.GROW,Data sources: United Nations World Population ...
610,611,ZMB,SP.POP.TOTL,Data sources : United Nations World Population...
611,612,ZWE,SP.POP.TOTL,Data sources : United Nations World Population...
612,613,ZWE,SP.POP.GROW,Data sources: United Nations World Population ...

In [27]:
edstats_country_series = edstats_country_series_df[['ID Unique','CountryCode','SeriesCode']].copy()
edstats_country_series.head()

   ID Unique CountryCode         SeriesCode
0          1         ABW        SP.POP.TOTL
1          2         ABW        SP.POP.GROW
2          3         AFG        SP.POP.GROW
3          4         AFG  NY.GDP.PCAP.PP.CD
4          5         AFG        SP.POP.TOTL

In [28]:
edstats_country_series = edstats_country_series.rename(columns={"ID Unique": "id_unique",
                                                                "CountryCode": "country_code",
                                                                "SeriesCode": "series_code"})
edstats_country_series

     id_unique country_code        series_code
0            1          ABW        SP.POP.TOTL
1            2          ABW        SP.POP.GROW
2            3          AFG        SP.POP.GROW
3            4          AFG  NY.GDP.PCAP.PP.CD
4            5          AFG        SP.POP.TOTL
5            6          AFG  NY.GDP.MKTP.PP.KD
6            7          AFG  NY.GNP.MKTP.PP.CD
7            8          AFG  NY.GDP.MKTP.PP.CD
8            9          AFG  NY.GDP.PCAP.PP.KD
9           10          AFG  NY.GNP.PCAP.PP.CD
10          11          AGO        SP.POP.TOTL
11          12          AGO        SP.POP.GROW
12          13          ALB        SP.POP.GROW
13          14          ALB        SP.POP.TOTL
14          15          AND        SP.POP.TOTL
15          16          AND        SP.POP.GROW
16          17          ARE        SP.POP.GROW
17          18          ARE        SP.POP.TOTL
18          19          ARG  NY.GDP.MKTP.PP.KD
19          20          ARG  NY.GNP.MKTP.PP.CD
20          21          ARG  NY.GDP.PCAP.PP.CD
21          22          ARG        SP.POP.TOTL
22          23          ARG  NY.GNP.PCAP.PP.CD
23          24          ARG  NY.GDP.PCAP.PP.KD
24          25          ARG        SP.POP.GROW
25          26          ARG  NY.GDP.MKTP.PP.CD
26          27          ARM        SP.POP.GROW
27          28          ARM        SP.POP.TOTL
28          29          ASM        SP.POP.TOTL
29          30          ASM        SP.POP.GROW
..         ...          ...                ...
583        584          UZB  NY.GDP.MKTP.PP.CD
584        585          VCT        SP.POP.TOTL
585        586          VCT        SP.POP.GROW
586        587          VEN        SP.POP.GROW
587        588          VEN        SP.POP.TOTL
588        589          VEN     NY.GNP.PCAP.CD
589        590          VIR        SP.POP.TOTL
590        591          VIR        SP.POP.GROW
591        592          VNM        SP.POP.GROW
592        593          VNM        SP.POP.TOTL
593        594          VUT        SP.POP.TOTL
594        595          VUT        SP.POP.GROW
595        596          WSM        SP.POP.GROW
596        597          WSM        SP.POP.TOTL
597        598          XKX        SP.POP.TOTL
598        599          XKX  NY.GDP.MKTP.PP.KD
599        600          XKX  NY.GNP.MKTP.PP.CD
600        601          XKX        SP.POP.GROW
601        602          XKX  NY.GDP.PCAP.PP.CD
602        603          XKX  NY.GNP.PCAP.PP.CD
603        604          XKX  NY.GDP.MKTP.PP.CD
604        605          XKX  NY.GDP.PCAP.PP.KD
605        606          YEM        SP.POP.GROW
606        607          YEM        SP.POP.TOTL
607        608          ZAF        SP.POP.TOTL
608        609          ZAF        SP.POP.GROW
609        610          ZMB        SP.POP.GROW
610        611          ZMB        SP.POP.TOTL
611        612          ZWE        SP.POP.TOTL
612        613          ZWE        SP.POP.GROW

[613 rows x 3 columns]

In [15]:
csv_file = "education-statistics/EdStatsSeries.csv"
edstats_series_df = pd.read_csv(csv_file)
edstats_series_df

,id_unique,Series Code,Topic,Indicator Name,Short definition,Long definition,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17
0,1,BAR.NOED.1519.FE.ZS,Attainment,Barro-Lee: Percentage of female population age...,Percentage of female population age 15-19 with...,Percentage of female population age 15-19 with...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,BAR.NOED.1519.ZS,Attainment,Barro-Lee: Percentage of population age 15-19 ...,Percentage of population age 15-19 with no edu...,Percentage of population age 15-19 with no edu...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,BAR.NOED.15UP.FE.ZS,Attainment,Barro-Lee: Percentage of female population age...,Percentage of female population age 15+ with n...,Percentage of female population age 15+ with n...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,BAR.NOED.15UP.ZS,Attainment,Barro-Lee: Percentage of population age 15+ wi...,Percentage of population age 15+ with no educa...,Percentage of population age 15+ with no educa...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,BAR.NOED.2024.FE.ZS,Attainment,Barro-Lee: Percentage of female population age...,Percentage of female population age 20-24 with...,Percentage of female population age 20-24 with...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,6,BAR.NOED.2024.ZS,Attainment,Barro-Lee: Percentage of population age 20-24 ...,Percentage of population age 20-24 with no edu...,Percentage of population age 20-24 with no edu...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,7,BAR.NOED.2529.FE.ZS,Attainment,Barro-Lee: Percentage of female population age...,Percentage of female population age 25-29 with...,Percentage of female population age 25-29 with...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,8,BAR.NOED.2529.ZS,Attainment,Barro-Lee: Percentage of population age 25-29 ...,Percentage of population age 25-29 with no edu...,Percentage of population age 25-29 with no edu...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,9,BAR.NOED.25UP.FE.ZS,Attainment,Barro-Lee: Percentage of female population age...,Percentage of female population age 25+ with n...,Percentage of female population age 25+ with n...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,10,BAR.NOED.25UP.ZS,Attainment,Barro-Lee: Percentage of population age 25+ wi...,Percentage of population age 25+ with no educa...,Percentage of population age 25+ with no educa...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,11,BAR.NOED.3034.FE.ZS,Attainment,Barro-Lee: Percentage of female population age...,Percentage of female population age 30-34 with...,Percentage of female population age 30-34 with...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,12,BAR.NOED.3034.ZS,Attainment,Barro-Lee: Percentage of population age 30-34 ...,Percentage of population age 30-34 with no edu...,Percentage of population age 30-34 with no edu...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,13,BAR.NOED.3539.FE.ZS,Attainment,Barro-Lee: Percentage of female population age...,Percentage of female population age 35-39 with...,Percentage of female population age 35-39 with...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,14,BAR.NOED.3539.ZS,Attainment,Barro-Lee: Percentage of population age 35-39 ...,Percentage of population age 35-39 with no edu...,Percentage of population age 35-39 with no edu...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,15,BAR.NOED.4044.FE.ZS,Attainment,Barro-Lee: Percentage of female population age...,Percentage of female population age 40-44 with...,Percentage of female population age 40-44 with...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,16,BAR.NOED.4044.ZS,Attainment,Barro-Lee: Percentage of population age 40-44 ...,Percentage of population age 40-44 with no edu...,Percentage of population age 40-44 with no edu...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,17,BAR.NOED.4549.FE.ZS,Attainment,Barro-Lee: Percentage of female population age...,Percentage of female population age 45-49 with...,Percentage of female population age 45-49 with...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,18,BAR.NOED.4549.ZS,Attainment,Barro-Lee: Percentage of population age 45-49 ...,Percentage of population age 45-49 with no edu...,Percentage of population age 45-49 with no edu...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,19,BAR.NOED.5054.FE.ZS,Attainment,Barro-Lee: Percentage of female population age...,Percentage of female population age 50-54 with...,Percentage of female population age 50-54 with...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,20,BAR.NOED.5054.ZS,Attainment,Barro-Lee: Percentage of population age 50-54 ...,Percentage of population age 50-54 with no edu...,Percentage of population age 50-54 with no edu...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,21,BAR.NOED.5559.FE.ZS,Attainment,Barro-Lee: Percentage of female population age...,Percentage of female population age 55-59 with...,Percentage of female population age 55-59 with...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,22,BAR.NOED.5559.ZS,Attainment,Barro-Lee: Percentage of population age 55-59 ...,Percentage of population age 55-59 with no edu...,Percentage of population age 55-59 with no edu...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,23,BAR.NOED.6064.FE.ZS,Attainment,Barro-Lee: Percentage of female population age...,Percentage of female population age 60-64 with...,Percentage of female population age 60-64 with...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,24,BAR.NOED.6064.ZS,Attainment,Barro-Lee: Percentage of population age 60-64 ...,Percentage of population age 60-64 with no edu...,Percentage of population age 60-64 with no edu...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,25,BAR.NOED.6569.FE.ZS,Attainment,Barro-Lee: Percentage of female population age...,Percentage of female population age 65-69 with...,Percentage of female population age 65-69 with...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,26,BAR.NOED.6569.ZS,Attainment,Barro-Lee: Percentage of population age 65-69 ...,Percentage of population age 65-69 with no edu...,Percentage of population age 65-69 with no edu...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,27,BAR.NOED.7074.FE.ZS,Attainment,Barro-Lee: Percentage of female population age...,Percentage of female population age 70-74 with...,Percentage of female population age 70-74 with...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,28,BAR.NOED.7074.ZS,Attainment,Barro-Lee: Percentage of population age 70-74 ...,Percentage of population age 70-74 with no edu...,Percentage of population age 70-74 with no edu...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,29,BAR.NOED.75UP.FE.ZS,Attainment,Barro-Lee: Percentage of female population age...,Percentage of female population age 75+ with n...,Percentage of female population age 75+ with n...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,30,BAR.NOED.75UP.ZS,Attainment,Barro-Lee: Percentage of population age 75+ wi...,Percentage of population age 75+ with no educa...,Percentage of population age 75+ with no educa...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3635,3636,UIS.XSPENDP.FDPUB.FNS,Expenditures,All staff compensation as % of total expenditu...,NaN,All staff (teacher and non-teachers) compensat...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UNESCO Institute for Statistics,NaN,NaN,NaN
3636,3637,UIS.XUNIT.GDPCAP.2.FSGOV,Expenditures,Government expenditure per lower secondary stu...,"Average total (current, capital and transfers)...","Average total (current, capital and transfers)...",NaN,NaN,NaN,Secondary,NaN,NaN,NaN,NaN,UNESCO Institute for Statistics,NaN,NaN,NaN
3637,3638,UIS.XUNIT.GDPCAP.3.FSGOV,Expenditures,Government expenditure per upper secondary stu...,NaN,"Average total (current, capital and transfers)...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UNESCO Institute for Statistics,NaN,NaN,NaN
3638,3639,UIS.XUNIT.GDPCAP.4.FSGOV,Expenditures,Government expenditure per post-secondary non-...,"Average total (current, capital and transfers)...","Average total (current, capital and transfers)...",NaN,NaN,NaN,Post-secondary,NaN,NaN,NaN,NaN,UNESCO Institute for Statistics,NaN,NaN,NaN
3639,3640,UIS.XUNIT.PPP.1.FSGOV,Expenditures,Government expenditure per primary student (PPP$),"Average total (current, capital and transfers)...","Average total (current, capital and transfers)...",NaN,NaN,NaN,Primary,NaN,NaN,NaN,NaN,UNESCO Institute for Statistics,NaN,NaN,NaN
3640,3641,UIS.XUNIT.PPP.2.FSGOV,Expenditures,Government expenditure per lower secondary stu...,"Average total (current, capital and transfers)...","Average total (current, capital and transfers)...",NaN,NaN,NaN,Secondary,NaN,NaN,NaN,NaN,UNESCO Institute for Statistics,NaN,NaN,NaN
3641,3642,UIS.XUNIT.PPP.23.FSGOV,Expenditures,Government expenditure per secondary student (...,"Average total (current, capital and transfers)...","Average total (current, capital and transfers)...",NaN,NaN,NaN,Secondary,NaN,NaN,NaN,NaN,UNESCO Institute for Statistics,NaN,NaN,NaN
3642,3643,UIS.XUNIT.PPP.3.FSGOV,Expenditures,Government expenditure per upper secondary stu...,NaN,"Average total (current, capital and transfers)...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UNESCO Institute for Statistics,NaN,NaN,NaN
3643,3644,UIS.XUNIT.PPP.4.FSGOV,Expenditures,Government expenditure per post-secondary non-...,"Average total (current, capital and transfers)...","Average total (current, capital and transfers)...",NaN,NaN,NaN,Post-secondary,NaN,NaN,NaN,NaN,UNESCO Institute for Statistics,NaN,NaN,NaN
3644,3645,UIS.XUNIT.PPP.56.FSGOV,Expenditures,Government expenditure per tertiary student (P...,"Average total (current, capital and transfers)...","Average total (current, capital and transfers)...",NaN,NaN,NaN,Tertiary,NaN,NaN,NaN,NaN,UNESCO Institute for Statistics,NaN,NaN,NaN
3645,3646,UIS.XUNIT.PPPCONST.1.FSGOV,Expenditures,Government expenditure per primary student (co...,"Average total (current, capital and transfers)...","Average total (current, capital and transfers)...",NaN,NaN,NaN,Primary,NaN,NaN,NaN,NaN,UNESCO Institute for Statistics,NaN,NaN,NaN
3646,3647,UIS.XUNIT.PPPCONST.2.FSGOV,Expenditures,Government expenditure per lower secondary stu...,"Average total (current, capital and transfers)...","Average total (current, capital and transfers)...",NaN,NaN,NaN,Secondary,NaN,NaN,NaN,NaN,UNESCO Institute for Statistics,NaN,NaN,NaN
3647,3648,UIS.XUNIT.PPPCONST.23.FSGOV,Expenditures,Government expenditure per secondary student (...,"Average total (current, capital and transfers)...","Average total (current, capital and transfers)...",NaN,NaN,NaN,Secondary,NaN,NaN,NaN,NaN,UNESCO Institute for Statistics,NaN,NaN,NaN
3648,3649,UIS.XUNIT.PPPCONST.3.FSGOV,Expenditures,Government expenditure per upper secondary stu...,NaN,"Average total (current, capital and transfers)...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UNESCO Institute for Statistics,NaN,NaN,NaN
3649,3650,UIS.XUNIT.PPPCONST.4.FSGOV,Expenditures,Government expenditure per post-secondary non-...,"Average total (current, capital and transfers)...","Average total (current, capital and transfers)...",NaN,NaN,NaN,Post-secondary,NaN,NaN,NaN,NaN,UNESCO Institute for Statistics,NaN,NaN,NaN
3650,3651,UIS.XUNIT.PPPCONST.56.FSGOV,Expenditures,Government expenditure per tertiary student (c...,"Average total (current, capital and transfers)...","Average total (current, capital and transfers)...",NaN,NaN,NaN,Tertiary,NaN,NaN,NaN,NaN,UNESCO Institute for Statistics,NaN,NaN,NaN
3651,3652,UIS.XUNIT.US.1.FSGOV,Expenditures,Government expenditure per primary student (US$),NaN,"Average total (current, capital and transfers)...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UNESCO Institute for Statistics,NaN,NaN,NaN
3652,3653,UIS.XUNIT.US.2.FSGOV,Expenditures,Government expenditure per lower secondary stu...,NaN,"Average total (current, capital and transfers)...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UNESCO Institute for Statistics,NaN,NaN,NaN
3653,3654,UIS.XUNIT.US.23.FSGOV,Expenditures,Government expenditure per secondary student (...,NaN,"Average total (current, capital and transfers)...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UNESCO Institute for Statistics,NaN,NaN,NaN
3654,3655,UIS.XUNIT.US.3.FSGOV,Expenditures,Government expenditure per upper secondary stu...,NaN,"Average total (current, capital and transfers)...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UNESCO Institute for Statistics,NaN,NaN,NaN
3655,3656,UIS.XUNIT.US.4.FSGOV,Expenditures,Government expenditure per post-secondary non-...,NaN,"Average total (current, capital and transfers)...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UNESCO Institute for Statistics,NaN,NaN,NaN
3656,3657,UIS.XUNIT.US.56.FSGOV,Expenditures,Government expenditure per tertiary student (US$),NaN,"Average total (current, capital and transfers)...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UNESCO Institute for Statistics,NaN,NaN,NaN
3657,3658,UIS.XUNIT.USCONST.1.FSGOV,Expenditures,Government expenditure per primary student (co...,NaN,"Average total (current, capital and transfers)...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UNESCO Institute for Statistics,NaN,NaN,NaN
3658,3659,UIS.XUNIT.USCONST.2.FSGOV,Expenditures,Government expenditure per lower secondary stu...,NaN,"Average total (current, capital and transfers)...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UNESCO Institute for Statistics,NaN,NaN,NaN
3659,3660,UIS.XUNIT.USCONST.23.FSGOV,Expenditures,Government expenditure per secondary student (...,NaN,"Average total (current, capital and transfers)...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UNESCO Institute for Statistics,NaN,NaN,NaN
3660,3661,UIS.XUNIT.USCONST.3.FSGOV,Expenditures,Government expenditure per upper secondary stu...,NaN,"Average total (current, capital and transfers)...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UNESCO Institute for Statistics,NaN,NaN,NaN
3661,3662,UIS.XUNIT.USCONST.4.FSGOV,Expenditures,Government expenditure per post-secondary non-...,NaN,"Average total (current, capital and transfers)...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UNESCO Institute for Statistics,NaN,NaN,NaN
3662,3663,UIS.XUNIT.USCONST.56.FSGOV,Expenditures,Government expenditure per tertiary student (c...,NaN,"Average total (current, capital and transfers)...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UNESCO Institute for Statistics,NaN,NaN,NaN
3663,3664,XGDP.23.FSGOV.FDINSTADM.FFD,Expenditures,Government expenditure in secondary institutio...,"Total general (local, regional and central) go...","Total general (local, regional and central) go...",NaN,NaN,NaN,Secondary,NaN,NaN,NaN,NaN,UNESCO Institute for Statistics,NaN,NaN,NaN
3664,3665,XGDP.56.FSGOV.FDINSTADM.FFD,Expenditures,Government expenditure in tertiary institution...,"Total general (local, regional and central) go...","Total general (local, regional and central) go...",NaN,NaN,NaN,Tertiary,NaN,NaN,NaN,NaN,UNESCO Institute for Statistics,NaN,NaN,NaN

In [21]:
edstats_series = edstats_series_df[['id_unique','Series Code', 'Topic', 'Indicator Name', 'Short definition']].copy()
edstats_series

,id_unique,Series Code,Topic,Indicator Name,Short definition
0,1,BAR.NOED.1519.FE.ZS,Attainment,Barro-Lee: Percentage of female population age...,Percentage of female population age 15-19 with...
1,2,BAR.NOED.1519.ZS,Attainment,Barro-Lee: Percentage of population age 15-19 ...,Percentage of population age 15-19 with no edu...
2,3,BAR.NOED.15UP.FE.ZS,Attainment,Barro-Lee: Percentage of female population age...,Percentage of female population age 15+ with n...
3,4,BAR.NOED.15UP.ZS,Attainment,Barro-Lee: Percentage of population age 15+ wi...,Percentage of population age 15+ with no educa...
4,5,BAR.NOED.2024.FE.ZS,Attainment,Barro-Lee: Percentage of female population age...,Percentage of female population age 20-24 with...
5,6,BAR.NOED.2024.ZS,Attainment,Barro-Lee: Percentage of population age 20-24 ...,Percentage of population age 20-24 with no edu...
6,7,BAR.NOED.2529.FE.ZS,Attainment,Barro-Lee: Percentage of female population age...,Percentage of female population age 25-29 with...
7,8,BAR.NOED.2529.ZS,Attainment,Barro-Lee: Percentage of population age 25-29 ...,Percentage of population age 25-29 with no edu...
8,9,BAR.NOED.25UP.FE.ZS,Attainment,Barro-Lee: Percentage of female population age...,Percentage of female population age 25+ with n...
9,10,BAR.NOED.25UP.ZS,Attainment,Barro-Lee: Percentage of population age 25+ wi...,Percentage of population age 25+ with no educa...
10,11,BAR.NOED.3034.FE.ZS,Attainment,Barro-Lee: Percentage of female population age...,Percentage of female population age 30-34 with...
11,12,BAR.NOED.3034.ZS,Attainment,Barro-Lee: Percentage of population age 30-34 ...,Percentage of population age 30-34 with no edu...
12,13,BAR.NOED.3539.FE.ZS,Attainment,Barro-Lee: Percentage of female population age...,Percentage of female population age 35-39 with...
13,14,BAR.NOED.3539.ZS,Attainment,Barro-Lee: Percentage of population age 35-39 ...,Percentage of population age 35-39 with no edu...
14,15,BAR.NOED.4044.FE.ZS,Attainment,Barro-Lee: Percentage of female population age...,Percentage of female population age 40-44 with...
15,16,BAR.NOED.4044.ZS,Attainment,Barro-Lee: Percentage of population age 40-44 ...,Percentage of population age 40-44 with no edu...
16,17,BAR.NOED.4549.FE.ZS,Attainment,Barro-Lee: Percentage of female population age...,Percentage of female population age 45-49 with...
17,18,BAR.NOED.4549.ZS,Attainment,Barro-Lee: Percentage of population age 45-49 ...,Percentage of population age 45-49 with no edu...
18,19,BAR.NOED.5054.FE.ZS,Attainment,Barro-Lee: Percentage of female population age...,Percentage of female population age 50-54 with...
19,20,BAR.NOED.5054.ZS,Attainment,Barro-Lee: Percentage of population age 50-54 ...,Percentage of population age 50-54 with no edu...
20,21,BAR.NOED.5559.FE.ZS,Attainment,Barro-Lee: Percentage of female population age...,Percentage of female population age 55-59 with...
21,22,BAR.NOED.5559.ZS,Attainment,Barro-Lee: Percentage of population age 55-59 ...,Percentage of population age 55-59 with no edu...
22,23,BAR.NOED.6064.FE.ZS,Attainment,Barro-Lee: Percentage of female population age...,Percentage of female population age 60-64 with...
23,24,BAR.NOED.6064.ZS,Attainment,Barro-Lee: Percentage of population age 60-64 ...,Percentage of population age 60-64 with no edu...
24,25,BAR.NOED.6569.FE.ZS,Attainment,Barro-Lee: Percentage of female population age...,Percentage of female population age 65-69 with...
25,26,BAR.NOED.6569.ZS,Attainment,Barro-Lee: Percentage of population age 65-69 ...,Percentage of population age 65-69 with no edu...
26,27,BAR.NOED.7074.FE.ZS,Attainment,Barro-Lee: Percentage of female population age...,Percentage of female population age 70-74 with...
27,28,BAR.NOED.7074.ZS,Attainment,Barro-Lee: Percentage of population age 70-74 ...,Percentage of population age 70-74 with no edu...
28,29,BAR.NOED.75UP.FE.ZS,Attainment,Barro-Lee: Percentage of female population age...,Percentage of female population age 75+ with n...
29,30,BAR.NOED.75UP.ZS,Attainment,Barro-Lee: Percentage of population age 75+ wi...,Percentage of population age 75+ with no educa...
...,...,...,...,...,...
3635,3636,UIS.XSPENDP.FDPUB.FNS,Expenditures,All staff compensation as % of total expenditu...,NaN
3636,3637,UIS.XUNIT.GDPCAP.2.FSGOV,Expenditures,Government expenditure per lower secondary stu...,"Average total (current, capital and transfers)..."
3637,3638,UIS.XUNIT.GDPCAP.3.FSGOV,Expenditures,Government expenditure per upper secondary stu...,NaN
3638,3639,UIS.XUNIT.GDPCAP.4.FSGOV,Expenditures,Government expenditure per post-secondary non-...,"Average total (current, capital and transfers)..."
3639,3640,UIS.XUNIT.PPP.1.FSGOV,Expenditures,Government expenditure per primary student (PPP$),"Average total (current, capital and transfers)..."
3640,3641,UIS.XUNIT.PPP.2.FSGOV,Expenditures,Government expenditure per lower secondary stu...,"Average total (current, capital and transfers)..."
3641,3642,UIS.XUNIT.PPP.23.FSGOV,Expenditures,Government expenditure per secondary student (...,"Average total (current, capital and transfers)..."
3642,3643,UIS.XUNIT.PPP.3.FSGOV,Expenditures,Government expenditure per upper secondary stu...,NaN
3643,3644,UIS.XUNIT.PPP.4.FSGOV,Expenditures,Government expenditure per post-secondary non-...,"Average total (current, capital and transfers)..."
3644,3645,UIS.XUNIT.PPP.56.FSGOV,Expenditures,Government expenditure per tertiary student (P...,"Average total (current, capital and transfers)..."
3645,3646,UIS.XUNIT.PPPCONST.1.FSGOV,Expenditures,Government expenditure per primary student (co...,"Average total (current, capital and transfers)..."
3646,3647,UIS.XUNIT.PPPCONST.2.FSGOV,Expenditures,Government expenditure per lower secondary stu...,"Average total (current, capital and transfers)..."
3647,3648,UIS.XUNIT.PPPCONST.23.FSGOV,Expenditures,Government expenditure per secondary student (...,"Average total (current, capital and transfers)..."
3648,3649,UIS.XUNIT.PPPCONST.3.FSGOV,Expenditures,Government expenditure per upper secondary stu...,NaN
3649,3650,UIS.XUNIT.PPPCONST.4.FSGOV,Expenditures,Government expenditure per post-secondary non-...,"Average total (current, capital and transfers)..."
3650,3651,UIS.XUNIT.PPPCONST.56.FSGOV,Expenditures,Government expenditure per tertiary student (c...,"Average total (current, capital and transfers)..."
3651,3652,UIS.XUNIT.US.1.FSGOV,Expenditures,Government expenditure per primary student (US$),NaN
3652,3653,UIS.XUNIT.US.2.FSGOV,Expenditures,Government expenditure per lower secondary stu...,NaN
3653,3654,UIS.XUNIT.US.23.FSGOV,Expenditures,Government expenditure per secondary student (...,NaN
3654,3655,UIS.XUNIT.US.3.FSGOV,Expenditures,Government expenditure per upper secondary stu...,NaN
3655,3656,UIS.XUNIT.US.4.FSGOV,Expenditures,Government expenditure per post-secondary non-...,NaN
3656,3657,UIS.XUNIT.US.56.FSGOV,Expenditures,Government expenditure per tertiary student (US$),NaN
3657,3658,UIS.XUNIT.USCONST.1.FSGOV,Expenditures,Government expenditure per primary student (co...,NaN
3658,3659,UIS.XUNIT.USCONST.2.FSGOV,Expenditures,Government expenditure per lower secondary stu...,NaN
3659,3660,UIS.XUNIT.USCONST.23.FSGOV,Expenditures,Government expenditure per secondary student (...,NaN
3660,3661,UIS.XUNIT.USCONST.3.FSGOV,Expenditures,Government expenditure per upper secondary stu...,NaN
3661,3662,UIS.XUNIT.USCONST.4.FSGOV,Expenditures,Government expenditure per post-secondary non-...,NaN
3662,3663,UIS.XUNIT.USCONST.56.FSGOV,Expenditures,Government expenditure per tertiary student (c...,NaN
3663,3664,XGDP.23.FSGOV.FDINSTADM.FFD,Expenditures,Government expenditure in secondary institutio...,"Total general (local, regional and central) go..."
3664,3665,XGDP.56.FSGOV.FDINSTADM.FFD,Expenditures,Government expenditure in tertiary institution...,"Total general (local, regional and central) go..."

In [22]:
edstats_series = edstats_series.rename(columns={"Series Code": "series_code",
                                                "Topic": "topic",
                                                "Indicator Name": "indicator_name",
                                                "Short definition":"short_definition"})
edstats_series

,id_unique,series_code,topic,indicator_name,short_definition
0,1,BAR.NOED.1519.FE.ZS,Attainment,Barro-Lee: Percentage of female population age...,Percentage of female population age 15-19 with...
1,2,BAR.NOED.1519.ZS,Attainment,Barro-Lee: Percentage of population age 15-19 ...,Percentage of population age 15-19 with no edu...
2,3,BAR.NOED.15UP.FE.ZS,Attainment,Barro-Lee: Percentage of female population age...,Percentage of female population age 15+ with n...
3,4,BAR.NOED.15UP.ZS,Attainment,Barro-Lee: Percentage of population age 15+ wi...,Percentage of population age 15+ with no educa...
4,5,BAR.NOED.2024.FE.ZS,Attainment,Barro-Lee: Percentage of female population age...,Percentage of female population age 20-24 with...
5,6,BAR.NOED.2024.ZS,Attainment,Barro-Lee: Percentage of population age 20-24 ...,Percentage of population age 20-24 with no edu...
6,7,BAR.NOED.2529.FE.ZS,Attainment,Barro-Lee: Percentage of female population age...,Percentage of female population age 25-29 with...
7,8,BAR.NOED.2529.ZS,Attainment,Barro-Lee: Percentage of population age 25-29 ...,Percentage of population age 25-29 with no edu...
8,9,BAR.NOED.25UP.FE.ZS,Attainment,Barro-Lee: Percentage of female population age...,Percentage of female population age 25+ with n...
9,10,BAR.NOED.25UP.ZS,Attainment,Barro-Lee: Percentage of population age 25+ wi...,Percentage of population age 25+ with no educa...
10,11,BAR.NOED.3034.FE.ZS,Attainment,Barro-Lee: Percentage of female population age...,Percentage of female population age 30-34 with...
11,12,BAR.NOED.3034.ZS,Attainment,Barro-Lee: Percentage of population age 30-34 ...,Percentage of population age 30-34 with no edu...
12,13,BAR.NOED.3539.FE.ZS,Attainment,Barro-Lee: Percentage of female population age...,Percentage of female population age 35-39 with...
13,14,BAR.NOED.3539.ZS,Attainment,Barro-Lee: Percentage of population age 35-39 ...,Percentage of population age 35-39 with no edu...
14,15,BAR.NOED.4044.FE.ZS,Attainment,Barro-Lee: Percentage of female population age...,Percentage of female population age 40-44 with...
15,16,BAR.NOED.4044.ZS,Attainment,Barro-Lee: Percentage of population age 40-44 ...,Percentage of population age 40-44 with no edu...
16,17,BAR.NOED.4549.FE.ZS,Attainment,Barro-Lee: Percentage of female population age...,Percentage of female population age 45-49 with...
17,18,BAR.NOED.4549.ZS,Attainment,Barro-Lee: Percentage of population age 45-49 ...,Percentage of population age 45-49 with no edu...
18,19,BAR.NOED.5054.FE.ZS,Attainment,Barro-Lee: Percentage of female population age...,Percentage of female population age 50-54 with...
19,20,BAR.NOED.5054.ZS,Attainment,Barro-Lee: Percentage of population age 50-54 ...,Percentage of population age 50-54 with no edu...
20,21,BAR.NOED.5559.FE.ZS,Attainment,Barro-Lee: Percentage of female population age...,Percentage of female population age 55-59 with...
21,22,BAR.NOED.5559.ZS,Attainment,Barro-Lee: Percentage of population age 55-59 ...,Percentage of population age 55-59 with no edu...
22,23,BAR.NOED.6064.FE.ZS,Attainment,Barro-Lee: Percentage of female population age...,Percentage of female population age 60-64 with...
23,24,BAR.NOED.6064.ZS,Attainment,Barro-Lee: Percentage of population age 60-64 ...,Percentage of population age 60-64 with no edu...
24,25,BAR.NOED.6569.FE.ZS,Attainment,Barro-Lee: Percentage of female population age...,Percentage of female population age 65-69 with...
25,26,BAR.NOED.6569.ZS,Attainment,Barro-Lee: Percentage of population age 65-69 ...,Percentage of population age 65-69 with no edu...
26,27,BAR.NOED.7074.FE.ZS,Attainment,Barro-Lee: Percentage of female population age...,Percentage of female population age 70-74 with...
27,28,BAR.NOED.7074.ZS,Attainment,Barro-Lee: Percentage of population age 70-74 ...,Percentage of population age 70-74 with no edu...
28,29,BAR.NOED.75UP.FE.ZS,Attainment,Barro-Lee: Percentage of female population age...,Percentage of female population age 75+ with n...
29,30,BAR.NOED.75UP.ZS,Attainment,Barro-Lee: Percentage of population age 75+ wi...,Percentage of population age 75+ with no educa...
...,...,...,...,...,...
3635,3636,UIS.XSPENDP.FDPUB.FNS,Expenditures,All staff compensation as % of total expenditu...,NaN
3636,3637,UIS.XUNIT.GDPCAP.2.FSGOV,Expenditures,Government expenditure per lower secondary stu...,"Average total (current, capital and transfers)..."
3637,3638,UIS.XUNIT.GDPCAP.3.FSGOV,Expenditures,Government expenditure per upper secondary stu...,NaN
3638,3639,UIS.XUNIT.GDPCAP.4.FSGOV,Expenditures,Government expenditure per post-secondary non-...,"Average total (current, capital and transfers)..."
3639,3640,UIS.XUNIT.PPP.1.FSGOV,Expenditures,Government expenditure per primary student (PPP$),"Average total (current, capital and transfers)..."
3640,3641,UIS.XUNIT.PPP.2.FSGOV,Expenditures,Government expenditure per lower secondary stu...,"Average total (current, capital and transfers)..."
3641,3642,UIS.XUNIT.PPP.23.FSGOV,Expenditures,Government expenditure per secondary student (...,"Average total (current, capital and transfers)..."
3642,3643,UIS.XUNIT.PPP.3.FSGOV,Expenditures,Government expenditure per upper secondary stu...,NaN
3643,3644,UIS.XUNIT.PPP.4.FSGOV,Expenditures,Government expenditure per post-secondary non-...,"Average total (current, capital and transfers)..."
3644,3645,UIS.XUNIT.PPP.56.FSGOV,Expenditures,Government expenditure per tertiary student (P...,"Average total (current, capital and transfers)..."
3645,3646,UIS.XUNIT.PPPCONST.1.FSGOV,Expenditures,Government expenditure per primary student (co...,"Average total (current, capital and transfers)..."
3646,3647,UIS.XUNIT.PPPCONST.2.FSGOV,Expenditures,Government expenditure per lower secondary stu...,"Average total (current, capital and transfers)..."
3647,3648,UIS.XUNIT.PPPCONST.23.FSGOV,Expenditures,Government expenditure per secondary student (...,"Average total (current, capital and transfers)..."
3648,3649,UIS.XUNIT.PPPCONST.3.FSGOV,Expenditures,Government expenditure per upper secondary stu...,NaN
3649,3650,UIS.XUNIT.PPPCONST.4.FSGOV,Expenditures,Government expenditure per post-secondary non-...,"Average total (current, capital and transfers)..."
3650,3651,UIS.XUNIT.PPPCONST.56.FSGOV,Expenditures,Government expenditure per tertiary student (c...,"Average total (current, capital and transfers)..."
3651,3652,UIS.XUNIT.US.1.FSGOV,Expenditures,Government expenditure per primary student (US$),NaN
3652,3653,UIS.XUNIT.US.2.FSGOV,Expenditures,Government expenditure per lower secondary stu...,NaN
3653,3654,UIS.XUNIT.US.23.FSGOV,Expenditures,Government expenditure per secondary student (...,NaN
3654,3655,UIS.XUNIT.US.3.FSGOV,Expenditures,Government expenditure per upper secondary stu...,NaN
3655,3656,UIS.XUNIT.US.4.FSGOV,Expenditures,Government expenditure per post-secondary non-...,NaN
3656,3657,UIS.XUNIT.US.56.FSGOV,Expenditures,Government expenditure per tertiary student (US$),NaN
3657,3658,UIS.XUNIT.USCONST.1.FSGOV,Expenditures,Government expenditure per primary student (co...,NaN
3658,3659,UIS.XUNIT.USCONST.2.FSGOV,Expenditures,Government expenditure per lower secondary stu...,NaN
3659,3660,UIS.XUNIT.USCONST.23.FSGOV,Expenditures,Government expenditure per secondary student (...,NaN
3660,3661,UIS.XUNIT.USCONST.3.FSGOV,Expenditures,Government expenditure per upper secondary stu...,NaN
3661,3662,UIS.XUNIT.USCONST.4.FSGOV,Expenditures,Government expenditure per post-secondary non-...,NaN
3662,3663,UIS.XUNIT.USCONST.56.FSGOV,Expenditures,Government expenditure per tertiary student (c...,NaN
3663,3664,XGDP.23.FSGOV.FDINSTADM.FFD,Expenditures,Government expenditure in secondary institutio...,"Total general (local, regional and central) go..."
3664,3665,XGDP.56.FSGOV.FDINSTADM.FFD,Expenditures,Government expenditure in tertiary institution...,"Total general (local, regional and central) go..."

In [23]:
engine.table_names()

['edstats_country_series', 'edstats_series', 'edstats_country']

In [29]:
edstats_country.to_sql(name='edstats_country', con=engine, if_exists='replace', index=True)

In [30]:
edstats_country_series.to_sql(name='edstats_country_series', con=engine, if_exists='replace', index=True)

In [25]:
edstats_series.to_sql(name='edstats_series', con=engine, if_exists='replace', index=True)

In [31]:
pd.read_sql_query('SELECT * from edstats_series', con=engine)

,index,id_unique,series_code,topic,indicator_name,short_definition
0,0,1,BAR.NOED.1519.FE.ZS,Attainment,Barro-Lee: Percentage of female population age...,Percentage of female population age 15-19 with...
1,1,2,BAR.NOED.1519.ZS,Attainment,Barro-Lee: Percentage of population age 15-19 ...,Percentage of population age 15-19 with no edu...
2,2,3,BAR.NOED.15UP.FE.ZS,Attainment,Barro-Lee: Percentage of female population age...,Percentage of female population age 15+ with n...
3,3,4,BAR.NOED.15UP.ZS,Attainment,Barro-Lee: Percentage of population age 15+ wi...,Percentage of population age 15+ with no educa...
4,4,5,BAR.NOED.2024.FE.ZS,Attainment,Barro-Lee: Percentage of female population age...,Percentage of female population age 20-24 with...
5,5,6,BAR.NOED.2024.ZS,Attainment,Barro-Lee: Percentage of population age 20-24 ...,Percentage of population age 20-24 with no edu...
6,6,7,BAR.NOED.2529.FE.ZS,Attainment,Barro-Lee: Percentage of female population age...,Percentage of female population age 25-29 with...
7,7,8,BAR.NOED.2529.ZS,Attainment,Barro-Lee: Percentage of population age 25-29 ...,Percentage of population age 25-29 with no edu...
8,8,9,BAR.NOED.25UP.FE.ZS,Attainment,Barro-Lee: Percentage of female population age...,Percentage of female population age 25+ with n...
9,9,10,BAR.NOED.25UP.ZS,Attainment,Barro-Lee: Percentage of population age 25+ wi...,Percentage of population age 25+ with no educa...
10,10,11,BAR.NOED.3034.FE.ZS,Attainment,Barro-Lee: Percentage of female population age...,Percentage of female population age 30-34 with...
11,11,12,BAR.NOED.3034.ZS,Attainment,Barro-Lee: Percentage of population age 30-34 ...,Percentage of population age 30-34 with no edu...
12,12,13,BAR.NOED.3539.FE.ZS,Attainment,Barro-Lee: Percentage of female population age...,Percentage of female population age 35-39 with...
13,13,14,BAR.NOED.3539.ZS,Attainment,Barro-Lee: Percentage of population age 35-39 ...,Percentage of population age 35-39 with no edu...
14,14,15,BAR.NOED.4044.FE.ZS,Attainment,Barro-Lee: Percentage of female population age...,Percentage of female population age 40-44 with...
15,15,16,BAR.NOED.4044.ZS,Attainment,Barro-Lee: Percentage of population age 40-44 ...,Percentage of population age 40-44 with no edu...
16,16,17,BAR.NOED.4549.FE.ZS,Attainment,Barro-Lee: Percentage of female population age...,Percentage of female population age 45-49 with...
17,17,18,BAR.NOED.4549.ZS,Attainment,Barro-Lee: Percentage of population age 45-49 ...,Percentage of population age 45-49 with no edu...
18,18,19,BAR.NOED.5054.FE.ZS,Attainment,Barro-Lee: Percentage of female population age...,Percentage of female population age 50-54 with...
19,19,20,BAR.NOED.5054.ZS,Attainment,Barro-Lee: Percentage of population age 50-54 ...,Percentage of population age 50-54 with no edu...
20,20,21,BAR.NOED.5559.FE.ZS,Attainment,Barro-Lee: Percentage of female population age...,Percentage of female population age 55-59 with...
21,21,22,BAR.NOED.5559.ZS,Attainment,Barro-Lee: Percentage of population age 55-59 ...,Percentage of population age 55-59 with no edu...
22,22,23,BAR.NOED.6064.FE.ZS,Attainment,Barro-Lee: Percentage of female population age...,Percentage of female population age 60-64 with...
23,23,24,BAR.NOED.6064.ZS,Attainment,Barro-Lee: Percentage of population age 60-64 ...,Percentage of population age 60-64 with no edu...
24,24,25,BAR.NOED.6569.FE.ZS,Attainment,Barro-Lee: Percentage of female population age...,Percentage of female population age 65-69 with...
25,25,26,BAR.NOED.6569.ZS,Attainment,Barro-Lee: Percentage of population age 65-69 ...,Percentage of population age 65-69 with no edu...
26,26,27,BAR.NOED.7074.FE.ZS,Attainment,Barro-Lee: Percentage of female population age...,Percentage of female population age 70-74 with...
27,27,28,BAR.NOED.7074.ZS,Attainment,Barro-Lee: Percentage of population age 70-74 ...,Percentage of population age 70-74 with no edu...
28,28,29,BAR.NOED.75UP.FE.ZS,Attainment,Barro-Lee: Percentage of female population age...,Percentage of female population age 75+ with n...
29,29,30,BAR.NOED.75UP.ZS,Attainment,Barro-Lee: Percentage of population age 75+ wi...,Percentage of population age 75+ with no educa...
...,...,...,...,...,...,...
3635,3634,3635,UIS.XSPENDP.FDPUB.FNNONS,Expenditures,Current expenditure other than staff compensat...,None
3636,3635,3636,UIS.XSPENDP.FDPUB.FNS,Expenditures,All staff compensation as % of total expenditu...,None
3637,3636,3637,UIS.XUNIT.GDPCAP.2.FSGOV,Expenditures,Government expenditure per lower secondary stu...,"Average total (current, capital and transfers)..."
3638,3637,3638,UIS.XUNIT.GDPCAP.3.FSGOV,Expenditures,Government expenditure per upper secondary stu...,None
3639,3638,3639,UIS.XUNIT.GDPCAP.4.FSGOV,Expenditures,Government expenditure per post-secondary non-...,"Average total (current, capital and transfers)..."
3640,3639,3640,UIS.XUNIT.PPP.1.FSGOV,Expenditures,Government expenditure per primary student (PPP$),"Average total (current, capital and transfers)..."
3641,3640,3641,UIS.XUNIT.PPP.2.FSGOV,Expenditures,Government expenditure per lower secondary stu...,"Average total (current, capital and transfers)..."
3642,3641,3642,UIS.XUNIT.PPP.23.FSGOV,Expenditures,Government expenditure per secondary student (...,"Average total (current, capital and transfers)..."
3643,3642,3643,UIS.XUNIT.PPP.3.FSGOV,Expenditures,Government expenditure per upper secondary stu...,None
3644,3643,3644,UIS.XUNIT.PPP.4.FSGOV,Expenditures,Government expenditure per post-secondary non-...,"Average total (current, capital and transfers)..."
3645,3644,3645,UIS.XUNIT.PPP.56.FSGOV,Expenditures,Government expenditure per tertiary student (P...,"Average total (current, capital and transfers)..."
3646,3645,3646,UIS.XUNIT.PPPCONST.1.FSGOV,Expenditures,Government expenditure per primary student (co...,"Average total (current, capital and transfers)..."
3647,3647,3648,UIS.XUNIT.PPPCONST.23.FSGOV,Expenditures,Government expenditure per secondary student (...,"Average total (current, capital and transfers)..."
3648,3648,3649,UIS.XUNIT.PPPCONST.3.FSGOV,Expenditures,Government expenditure per upper secondary stu...,None
3649,3649,3650,UIS.XUNIT.PPPCONST.4.FSGOV,Expenditures,Government expenditure per post-secondary non-...,"Average total (current, capital and transfers)..."
3650,3650,3651,UIS.XUNIT.PPPCONST.56.FSGOV,Expenditures,Government expenditure per tertiary student (c...,"Average total (current, capital and transfers)..."
3651,3651,3652,UIS.XUNIT.US.1.FSGOV,Expenditures,Government expenditure per primary student (US$),None
3652,3652,3653,UIS.XUNIT.US.2.FSGOV,Expenditures,Government expenditure per lower secondary stu...,None
3653,3653,3654,UIS.XUNIT.US.23.FSGOV,Expenditures,Government expenditure per secondary student (...,None
3654,3654,3655,UIS.XUNIT.US.3.FSGOV,Expenditures,Government expenditure per upper secondary stu...,None
3655,3655,3656,UIS.XUNIT.US.4.FSGOV,Expenditures,Government expenditure per post-secondary non-...,None
3656,3656,3657,UIS.XUNIT.US.56.FSGOV,Expenditures,Government expenditure per tertiary student (US$),None
3657,3657,3658,UIS.XUNIT.USCONST.1.FSGOV,Expenditures,Government expenditure per primary student (co...,None
3658,3658,3659,UIS.XUNIT.USCONST.2.FSGOV,Expenditures,Government expenditure per lower secondary stu...,None
3659,3659,3660,UIS.XUNIT.USCONST.23.FSGOV,Expenditures,Government expenditure per secondary student (...,None
3660,3660,3661,UIS.XUNIT.USCONST.3.FSGOV,Expenditures,Government expenditure per upper secondary stu...,None
3661,3661,3662,UIS.XUNIT.USCONST.4.FSGOV,Expenditures,Government expenditure per post-secondary non-...,None
3662,3662,3663,UIS.XUNIT.USCONST.56.FSGOV,Expenditures,Government expenditure per tertiary student (c...,None
3663,3663,3664,XGDP.23.FSGOV.FDINSTADM.FFD,Expenditures,Government expenditure in secondary institutio...,"Total general (local, regional and central) go..."
3664,3664,3665,XGDP.56.FSGOV.FDINSTADM.FFD,Expenditures,Government expenditure in tertiary institution...,"Total general (local, regional and central) go..."

In [6]:
pd.read_sql_query('SELECT * from edstats_country_series', con=engine)

     index  id_unique country_code        series_code
0        0          1          ABW        SP.POP.TOTL
1        1          2          ABW        SP.POP.GROW
2        2          3          AFG        SP.POP.GROW
3        3          4          AFG  NY.GDP.PCAP.PP.CD
4        4          5          AFG        SP.POP.TOTL
5        5          6          AFG  NY.GDP.MKTP.PP.KD
6        6          7          AFG  NY.GNP.MKTP.PP.CD
7        7          8          AFG  NY.GDP.MKTP.PP.CD
8        8          9          AFG  NY.GDP.PCAP.PP.KD
9        9         10          AFG  NY.GNP.PCAP.PP.CD
10      10         11          AGO        SP.POP.TOTL
11      11         12          AGO        SP.POP.GROW
12      12         13          ALB        SP.POP.GROW
13      13         14          ALB        SP.POP.TOTL
14      14         15          AND        SP.POP.TOTL
15      15         16          AND        SP.POP.GROW
16      16         17          ARE        SP.POP.GROW
17      17         18          ARE        SP.POP.TOTL
18      18         19          ARG  NY.GDP.MKTP.PP.KD
19      19         20          ARG  NY.GNP.MKTP.PP.CD
20      20         21          ARG  NY.GDP.PCAP.PP.CD
21      21         22          ARG        SP.POP.TOTL
22      22         23          ARG  NY.GNP.PCAP.PP.CD
23      23         24          ARG  NY.GDP.PCAP.PP.KD
24      24         25          ARG        SP.POP.GROW
25      25         26          ARG  NY.GDP.MKTP.PP.CD
26      26         27          ARM        SP.POP.GROW
27      27         28          ARM        SP.POP.TOTL
28      28         29          ASM        SP.POP.TOTL
29      29         30          ASM        SP.POP.GROW
..     ...        ...          ...                ...
583    583        584          UZB  NY.GDP.MKTP.PP.CD
584    584        585          VCT        SP.POP.TOTL
585    585        586          VCT        SP.POP.GROW
586    586        587          VEN        SP.POP.GROW
587    587        588          VEN        SP.POP.TOTL
588    588        589          VEN     NY.GNP.PCAP.CD
589    589        590          VIR        SP.POP.TOTL
590    590        591          VIR        SP.POP.GROW
591    591        592          VNM        SP.POP.GROW
592    592        593          VNM        SP.POP.TOTL
593    593        594          VUT        SP.POP.TOTL
594    594        595          VUT        SP.POP.GROW
595    595        596          WSM        SP.POP.GROW
596    596        597          WSM        SP.POP.TOTL
597    597        598          XKX        SP.POP.TOTL
598    598        599          XKX  NY.GDP.MKTP.PP.KD
599    599        600          XKX  NY.GNP.MKTP.PP.CD
600    600        601          XKX        SP.POP.GROW
601    601        602          XKX  NY.GDP.PCAP.PP.CD
602    602        603          XKX  NY.GNP.PCAP.PP.CD
603    603        604          XKX  NY.GDP.MKTP.PP.CD
604    604        605          XKX  NY.GDP.PCAP.PP.KD
605    605        606          YEM        SP.POP.GROW
606    606        607          YEM        SP.POP.TOTL
607    607        608          ZAF        SP.POP.TOTL
608    608        609          ZAF        SP.POP.GROW
609    609        610          ZMB        SP.POP.GROW
610    610        611          ZMB        SP.POP.TOTL
611    611        612          ZWE        SP.POP.TOTL
612    612        613          ZWE        SP.POP.GROW

[613 rows x 4 columns]

In [32]:
pd.read_sql_query('SELECT * from edstats_country', con=engine)

,index,country_code,short_name,proper_name,long_name,two_alpha_code,currency_unit,region,income_group
0,0,ABW,Aruba,Aruba,Aruba,AW,Aruban florin,Latin America & Caribbean,High income: nonOECD
1,1,AFG,Afghanistan,Afghanistan,Islamic State of Afghanistan,AF,Afghan afghani,South Asia,Low income
2,2,AGO,Angola,Angola,People's Republic of Angola,AO,Angolan kwanza,Sub-Saharan Africa,Upper middle income
3,3,ALB,Albania,Albania,Republic of Albania,AL,Albanian lek,Europe & Central Asia,Upper middle income
4,4,AND,Andorra,Andorra,Principality of Andorra,AD,Euro,Europe & Central Asia,High income: nonOECD
5,5,ARB,Arab World,Arab World,Arab World,1A,None,None,None
6,6,ARE,United Arab Emirates,United Arab Emirates,United Arab Emirates,AE,U.A.E. dirham,Middle East & North Africa,High income: nonOECD
7,7,ARG,Argentina,Argentina,Argentine Republic,AR,Argentine peso,Latin America & Caribbean,Upper middle income
8,8,ARM,Armenia,Armenia,Republic of Armenia,AM,Armenian dram,Europe & Central Asia,Lower middle income
9,9,ASM,American Samoa,American Samoa,American Samoa,AS,U.S. dollar,East Asia & Pacific,Upper middle income
10,10,ATG,Antigua and Barbuda,Antigua and Barbuda,Antigua and Barbuda,AG,East Caribbean dollar,Latin America & Caribbean,High income: nonOECD
11,11,AUS,Australia,Australia,Commonwealth of Australia,AU,Australian dollar,East Asia & Pacific,High income: OECD
12,12,AUT,Austria,Austria,Republic of Austria,AT,Euro,Europe & Central Asia,High income: OECD
13,13,AZE,Azerbaijan,Azerbaijan,Republic of Azerbaijan,AZ,New Azeri manat,Europe & Central Asia,Upper middle income
14,14,BDI,Burundi,Burundi,Republic of Burundi,BI,Burundi franc,Sub-Saharan Africa,Low income
15,15,BEL,Belgium,Belgium,Kingdom of Belgium,BE,Euro,Europe & Central Asia,High income: OECD
16,16,BEN,Benin,Benin,Republic of Benin,BJ,CFA franc,Sub-Saharan Africa,Low income
17,17,BFA,Burkina Faso,Burkina Faso,Burkina Faso,BF,CFA franc,Sub-Saharan Africa,Low income
18,18,BGD,Bangladesh,Bangladesh,People's Republic of Bangladesh,BD,Bangladeshi taka,South Asia,Low income
19,19,BGR,Bulgaria,Bulgaria,Republic of Bulgaria,BG,Bulgarian lev,Europe & Central Asia,Upper middle income
20,20,BHR,Bahrain,Bahrain,Kingdom of Bahrain,BH,Bahraini dinar,Middle East & North Africa,High income: nonOECD
21,21,BHS,The Bahamas,"Bahamas, The",Commonwealth of The Bahamas,BS,Bahamian dollar,Latin America & Caribbean,High income: nonOECD
22,22,BIH,Bosnia and Herzegovina,Bosnia and Herzegovina,Bosnia and Herzegovina,BA,Bosnia and Herzegovina convertible mark,Europe & Central Asia,Upper middle income
23,23,BLR,Belarus,Belarus,Republic of Belarus,BY,Belarusian rubel,Europe & Central Asia,Upper middle income
24,24,BLZ,Belize,Belize,Belize,BZ,Belize dollar,Latin America & Caribbean,Upper middle income
25,25,BMU,Bermuda,Bermuda,The Bermudas,BM,Bermuda dollar,North America,High income: nonOECD
26,26,BOL,Bolivia,Bolivia,Plurinational State of Bolivia,BO,Bolivian Boliviano,Latin America & Caribbean,Lower middle income
27,27,BRA,Brazil,Brazil,Federative Republic of Brazil,BR,Brazilian real,Latin America & Caribbean,Upper middle income
28,28,BRB,Barbados,Barbados,Barbados,BB,Barbados dollar,Latin America & Caribbean,High income: nonOECD
29,29,BRN,Brunei,Brunei Darussalam,Brunei Darussalam,BN,Brunei dollar,East Asia & Pacific,High income: nonOECD
...,...,...,...,...,...,...,...,...,...
211,211,TCD,Chad,Chad,Republic of Chad,TD,CFA franc,Sub-Saharan Africa,Low income
212,212,TGO,Togo,Togo,Republic of Togo,TG,CFA franc,Sub-Saharan Africa,Low income
213,213,THA,Thailand,Thailand,Kingdom of Thailand,TH,Thai baht,East Asia & Pacific,Upper middle income
214,214,TJK,Tajikistan,Tajikistan,Republic of Tajikistan,TJ,Tajik somoni,Europe & Central Asia,Low income
215,215,TKM,Turkmenistan,Turkmenistan,Turkmenistan,TM,New Turkmen manat,Europe & Central Asia,Upper middle income
216,216,TLS,Timor-Leste,Timor-Leste,Democratic Republic of Timor-Leste,TL,U.S. dollar,East Asia & Pacific,Lower middle income
217,217,TON,Tonga,Tonga,Kingdom of Tonga,TO,Tongan pa'anga,East Asia & Pacific,Upper middle income
218,218,TTO,Trinidad and Tobago,Trinidad and Tobago,Republic of Trinidad and Tobago,TT,Trinidad and Tobago dollar,Latin America & Caribbean,High income: nonOECD
219,219,TUN,Tunisia,Tunisia,Republic of Tunisia,TN,Tunisian dinar,Middle East & North Africa,Upper middle income
220,220,TUR,Turkey,Turkey,Republic of Turkey,TR,New Turkish lira,Europe & Central Asia,Upper middle income
221,221,TUV,Tuvalu,Tuvalu,Tuvalu,TV,Australian dollar,East Asia & Pacific,Upper middle income
222,222,TZA,Tanzania,Tanzania,United Republic of Tanzania,TZ,Tanzanian shilling,Sub-Saharan Africa,Low income
223,223,UGA,Uganda,Uganda,Republic of Uganda,UG,Ugandan shilling,Sub-Saharan Africa,Low income
224,224,UKR,Ukraine,Ukraine,Ukraine,UA,Ukrainian hryvnia,Europe & Central Asia,Lower middle income
225,225,UMC,Upper middle income,Upper middle income,Upper middle income,XT,None,None,None
226,226,URY,Uruguay,Uruguay,Oriental Republic of Uruguay,UY,Uruguayan peso,Latin America & Caribbean,High income: nonOECD
227,227,USA,United States,United States,United States of America,US,U.S. dollar,North America,High income: OECD
228,228,UZB,Uzbekistan,Uzbekistan,Republic of Uzbekistan,UZ,Uzbek sum,Europe & Central Asia,Lower middle income
229,229,VCT,St. Vincent and the Grenadines,St. Vincent and the Grenadines,St. Vincent and the Grenadines,VC,East Caribbean dollar,Latin America & Caribbean,Upper middle income
230,230,VEN,Venezuela,"Venezuela, RB",República Bolivariana de Venezuela,VE,Venezuelan bolivar fuerte,Latin America & Caribbean,Upper middle income
231,231,VIR,Virgin Islands,Virgin Islands (U.S.),Virgin Islands of the United States,VI,U.S. dollar,Latin America & Caribbean,High income: nonOECD
232,232,VNM,Vietnam,Vietnam,Socialist Republic of Vietnam,VN,Vietnamese dong,East Asia & Pacific,Lower middle income
233,233,VUT,Vanuatu,Vanuatu,Republic of Vanuatu,VU,Vanuatu vatu,East Asia & Pacific,Lower middle income
234,234,WLD,World,World,World,1W,None,None,None
235,235,WSM,Samoa,Samoa,Samoa,WS,Samoan tala,East Asia & Pacific,Lower middle income
236,236,XKX,Kosovo,Kosovo,Republic of Kosovo,None,Euro,Europe & Central Asia,Lower middle income
237,237,YEM,Yemen,"Yemen, Rep.",Republic of Yemen,YE,Yemeni rial,Middle East & North Africa,Lower middle income
238,238,ZAF,South Africa,South Africa,Republic of South Africa,ZA,South African rand,Sub-Saharan Africa,Upper middle income
239,239,ZMB,Zambia,Zambia,Republic of Zambia,ZM,New Zambian kwacha,Sub-Saharan Africa,Lower middle income
240,240,ZWE,Zimbabwe,Zimbabwe,Republic of Zimbabwe,ZW,U.S. dollar,Sub-Saharan Africa,Low income

In [33]:
pd.read_sql_query('SELECT edstats_country.short_name,edstats_country.proper_name,edstats_country.long_name,edstats_country.two_alpha_code,edstats_country.currency_unit,edstats_country.region,edstats_country.income_group, edstats_country.country_code, edstats_country_series.series_code,edstats_series.topic,edstats_series.indicator_name,edstats_series.short_definition FROM edstats_country_series INNER JOIN edstats_country ON edstats_country.country_code=edstats_country_series.country_code INNER JOIN edstats_series ON edstats_country_series.series_code=edstats_series.series_code;', con=engine)

,short_name,proper_name,long_name,two_alpha_code,currency_unit,region,income_group,country_code,series_code,topic,indicator_name,short_definition
0,Aruba,Aruba,Aruba,AW,Aruban florin,Latin America & Caribbean,High income: nonOECD,ABW,SP.POP.TOTL,Health: Population: Structure,"Population, total",None
1,Aruba,Aruba,Aruba,AW,Aruban florin,Latin America & Caribbean,High income: nonOECD,ABW,SP.POP.GROW,Health: Population: Dynamics,Population growth (annual %),Annual population growth rate. Population is b...
2,Afghanistan,Afghanistan,Islamic State of Afghanistan,AF,Afghan afghani,South Asia,Low income,AFG,SP.POP.GROW,Health: Population: Dynamics,Population growth (annual %),Annual population growth rate. Population is b...
3,Afghanistan,Afghanistan,Islamic State of Afghanistan,AF,Afghan afghani,South Asia,Low income,AFG,NY.GDP.PCAP.PP.CD,Economic Policy & Debt: Purchasing power parity,"GDP per capita, PPP (current international $)",None
4,Afghanistan,Afghanistan,Islamic State of Afghanistan,AF,Afghan afghani,South Asia,Low income,AFG,SP.POP.TOTL,Health: Population: Structure,"Population, total",None
5,Afghanistan,Afghanistan,Islamic State of Afghanistan,AF,Afghan afghani,South Asia,Low income,AFG,NY.GDP.MKTP.PP.KD,Economic Policy & Debt: Purchasing power parity,"GDP, PPP (constant 2011 international $)",None
6,Afghanistan,Afghanistan,Islamic State of Afghanistan,AF,Afghan afghani,South Asia,Low income,AFG,NY.GNP.MKTP.PP.CD,Economic Policy & Debt: Purchasing power parity,"GNI, PPP (current international $)",None
7,Afghanistan,Afghanistan,Islamic State of Afghanistan,AF,Afghan afghani,South Asia,Low income,AFG,NY.GDP.MKTP.PP.CD,Economic Policy & Debt: Purchasing power parity,"GDP, PPP (current international $)",None
8,Afghanistan,Afghanistan,Islamic State of Afghanistan,AF,Afghan afghani,South Asia,Low income,AFG,NY.GDP.PCAP.PP.KD,Economic Policy & Debt: Purchasing power parity,"GDP per capita, PPP (constant 2011 internation...",None
9,Afghanistan,Afghanistan,Islamic State of Afghanistan,AF,Afghan afghani,South Asia,Low income,AFG,NY.GNP.PCAP.PP.CD,Economic Policy & Debt: Purchasing power parity,"GNI per capita, PPP (current international $)",None
10,Angola,Angola,People's Republic of Angola,AO,Angolan kwanza,Sub-Saharan Africa,Upper middle income,AGO,SP.POP.TOTL,Health: Population: Structure,"Population, total",None
11,Angola,Angola,People's Republic of Angola,AO,Angolan kwanza,Sub-Saharan Africa,Upper middle income,AGO,SP.POP.GROW,Health: Population: Dynamics,Population growth (annual %),Annual population growth rate. Population is b...
12,Albania,Albania,Republic of Albania,AL,Albanian lek,Europe & Central Asia,Upper middle income,ALB,SP.POP.GROW,Health: Population: Dynamics,Population growth (annual %),Annual population growth rate. Population is b...
13,Albania,Albania,Republic of Albania,AL,Albanian lek,Europe & Central Asia,Upper middle income,ALB,SP.POP.TOTL,Health: Population: Structure,"Population, total",None
14,Andorra,Andorra,Principality of Andorra,AD,Euro,Europe & Central Asia,High income: nonOECD,AND,SP.POP.TOTL,Health: Population: Structure,"Population, total",None
15,Andorra,Andorra,Principality of Andorra,AD,Euro,Europe & Central Asia,High income: nonOECD,AND,SP.POP.GROW,Health: Population: Dynamics,Population growth (annual %),Annual population growth rate. Population is b...
16,United Arab Emirates,United Arab Emirates,United Arab Emirates,AE,U.A.E. dirham,Middle East & North Africa,High income: nonOECD,ARE,SP.POP.GROW,Health: Population: Dynamics,Population growth (annual %),Annual population growth rate. Population is b...
17,United Arab Emirates,United Arab Emirates,United Arab Emirates,AE,U.A.E. dirham,Middle East & North Africa,High income: nonOECD,ARE,SP.POP.TOTL,Health: Population: Structure,"Population, total",None
18,Argentina,Argentina,Argentine Republic,AR,Argentine peso,Latin America & Caribbean,Upper middle income,ARG,NY.GDP.MKTP.PP.KD,Economic Policy & Debt: Purchasing power parity,"GDP, PPP (constant 2011 international $)",None
19,Argentina,Argentina,Argentine Republic,AR,Argentine peso,Latin America & Caribbean,Upper middle income,ARG,NY.GNP.MKTP.PP.CD,Economic Policy & Debt: Purchasing power parity,"GNI, PPP (current international $)",None
20,Argentina,Argentina,Argentine Republic,AR,Argentine peso,Latin America & Caribbean,Upper middle income,ARG,NY.GDP.PCAP.PP.CD,Economic Policy & Debt: Purchasing power parity,"GDP per capita, PPP (current international $)",None
21,Argentina,Argentina,Argentine Republic,AR,Argentine peso,Latin America & Caribbean,Upper middle income,ARG,SP.POP.TOTL,Health: Population: Structure,"Population, total",None
22,Argentina,Argentina,Argentine Republic,AR,Argentine peso,Latin America & Caribbean,Upper middle income,ARG,NY.GNP.PCAP.PP.CD,Economic Policy & Debt: Purchasing power parity,"GNI per capita, PPP (current international $)",None
23,Argentina,Argentina,Argentine Republic,AR,Argentine peso,Latin America & Caribbean,Upper middle income,ARG,NY.GDP.PCAP.PP.KD,Economic Policy & Debt: Purchasing power parity,"GDP per capita, PPP (constant 2011 internation...",None
24,Argentina,Argentina,Argentine Republic,AR,Argentine peso,Latin America & Caribbean,Upper middle income,ARG,SP.POP.GROW,Health: Population: Dynamics,Population growth (annual %),Annual population growth rate. Population is b...
25,Argentina,Argentina,Argentine Republic,AR,Argentine peso,Latin America & Caribbean,Upper middle income,ARG,NY.GDP.MKTP.PP.CD,Economic Policy & Debt: Purchasing power parity,"GDP, PPP (current international $)",None
26,Armenia,Armenia,Republic of Armenia,AM,Armenian dram,Europe & Central Asia,Lower middle income,ARM,SP.POP.GROW,Health: Population: Dynamics,Population growth (annual %),Annual population growth rate. Population is b...
27,Armenia,Armenia,Republic of Armenia,AM,Armenian dram,Europe & Central Asia,Lower middle income,ARM,SP.POP.TOTL,Health: Population: Structure,"Population, total",None
28,American Samoa,American Samoa,American Samoa,AS,U.S. dollar,East Asia & Pacific,Upper middle income,ASM,SP.POP.TOTL,Health: Population: Structure,"Population, total",None
29,American Samoa,American Samoa,American Samoa,AS,U.S. dollar,East Asia & Pacific,Upper middle income,ASM,SP.POP.GROW,Health: Population: Dynamics,Population growth (annual %),Annual population growth rate. Population is b...
...,...,...,...,...,...,...,...,...,...,...,...,...
583,Uzbekistan,Uzbekistan,Republic of Uzbekistan,UZ,Uzbek sum,Europe & Central Asia,Lower middle income,UZB,NY.GDP.MKTP.PP.CD,Economic Policy & Debt: Purchasing power parity,"GDP, PPP (current international $)",None
584,St. Vincent and the Grenadines,St. Vincent and the Grenadines,St. Vincent and the Grenadines,VC,East Caribbean dollar,Latin America & Caribbean,Upper middle income,VCT,SP.POP.TOTL,Health: Population: Structure,"Population, total",None
585,St. Vincent and the Grenadines,St. Vincent and the Grenadines,St. Vincent and the Grenadines,VC,East Caribbean dollar,Latin America & Caribbean,Upper middle income,VCT,SP.POP.GROW,Health: Population: Dynamics,Population growth (annual %),Annual population growth rate. Population is b...
586,Venezuela,"Venezuela, RB",República Bolivariana de Venezuela,VE,Venezuelan bolivar fuerte,Latin America & Caribbean,Upper middle income,VEN,SP.POP.GROW,Health: Population: Dynamics,Population growth (annual %),Annual population growth rate. Population is b...
587,Venezuela,"Venezuela, RB",República Bolivariana de Venezuela,VE,Venezuelan bolivar fuerte,Latin America & Caribbean,Upper middle income,VEN,SP.POP.TOTL,Health: Population: Structure,"Population, total",None
588,Venezuela,"Venezuela, RB",República Bolivariana de Venezuela,VE,Venezuelan bolivar fuerte,Latin America & Caribbean,Upper middle income,VEN,NY.GNP.PCAP.CD,Economic Policy & Debt: National accounts: Atl...,"GNI per capita, Atlas method (current US$)",None
589,Virgin Islands,Virgin Islands (U.S.),Virgin Islands of the United States,VI,U.S. dollar,Latin America & Caribbean,High income: nonOECD,VIR,SP.POP.TOTL,Health: Population: Structure,"Population, total",None
590,Virgin Islands,Virgin Islands (U.S.),Virgin Islands of the United States,VI,U.S. dollar,Latin America & Caribbean,High income: nonOECD,VIR,SP.POP.GROW,Health: Population: Dynamics,Population growth (annual %),Annual population growth rate. Population is b...
591,Vietnam,Vietnam,Socialist Republic of Vietnam,VN,Vietnamese dong,East Asia & Pacific,Lower middle income,VNM,SP.POP.GROW,Health: Population: Dynamics,Population growth (annual %),Annual population growth rate. Population is b...
592,Vietnam,Vietnam,Socialist Republic of Vietnam,VN,Vietnamese dong,East Asia & Pacific,Lower middle income,VNM,SP.POP.TOTL,Health: Population: Structure,"Population, total",None
593,Vanuatu,Vanuatu,Republic of Vanuatu,VU,Vanuatu vatu,East Asia & Pacific,Lower middle income,VUT,SP.POP.TOTL,Health: Population: Structure,"Population, total",None
594,Vanuatu,Vanuatu,Republic of Vanuatu,VU,Vanuatu vatu,East Asia & Pacific,Lower middle income,VUT,SP.POP.GROW,Health: Population: Dynamics,Population growth (annual %),Annual population growth rate. Population is b...
595,Samoa,Samoa,Samoa,WS,Samoan tala,East Asia & Pacific,Lower middle income,WSM,SP.POP.GROW,Health: Population: Dynamics,Population growth (annual %),Annual population growth rate. Population is b...
596,Samoa,Samoa,Samoa,WS,Samoan tala,East Asia & Pacific,Lower middle income,WSM,SP.POP.TOTL,Health: Population: Structure,"Population, total",None
597,Kosovo,Kosovo,Republic of Kosovo,None,Euro,Europe & Central Asia,Lower middle income,XKX,SP.POP.TOTL,Health: Population: Structure,"Population, total",None
598,Kosovo,Kosovo,Republic of Kosovo,None,Euro,Europe & Central Asia,Lower middle income,XKX,NY.GDP.MKTP.PP.KD,Economic Policy & Debt: Purchasing power parity,"GDP, PPP (constant 2011 international $)",None
599,Kosovo,Kosovo,Republic of Kosovo,None,Euro,Europe & Central Asia,Lower middle income,XKX,NY.GNP.MKTP.PP.CD,Economic Policy & Debt: Purchasing power parity,"GNI, PPP (current international $)",None
600,Kosovo,Kosovo,Republic of Kosovo,None,Euro,Europe & Central Asia,Lower middle income,XKX,SP.POP.GROW,Health: Population: Dynamics,Population growth (annual %),Annual population growth rate. Population is b...
601,Kosovo,Kosovo,Republic of Kosovo,None,Euro,Europe & Central Asia,Lower middle income,XKX,NY.GDP.PCAP.PP.CD,Economic Policy & Debt: Purchasing power parity,"GDP per capita, PPP (current international $)",None
602,Kosovo,Kosovo,Republic of Kosovo,None,Euro,Europe & Central Asia,Lower middle income,XKX,NY.GNP.PCAP.PP.CD,Economic Policy & Debt: Purchasing power parity,"GNI per capita, PPP (current international $)",None
603,Kosovo,Kosovo,Republic of Kosovo,None,Euro,Europe & Central Asia,Lower middle income,XKX,NY.GDP.MKTP.PP.CD,Economic Policy & Debt: Purchasing power parity,"GDP, PPP (current international $)",None
604,Kosovo,Kosovo,Republic of Kosovo,None,Euro,Europe & Central Asia,Lower middle income,XKX,NY.GDP.PCAP.PP.KD,Economic Policy & Debt: Purchasing power parity,"GDP per capita, PPP (constant 2011 internation...",None
605,Yemen,"Yemen, Rep.",Republic of Yemen,YE,Yemeni rial,Middle East & North Africa,Lower middle income,YEM,SP.POP.GROW,Health: Population: Dynamics,Population growth (annual %),Annual population growth rate. Population is b...
606,Yemen,"Yemen, Rep.",Republic of Yemen,YE,Yemeni rial,Middle East & North Africa,Lower middle income,YEM,SP.POP.TOTL,Health: Population: Structure,"Population, total",None
607,South Africa,South Africa,Republic of South Africa,ZA,South African rand,Sub-Saharan Africa,Upper middle income,ZAF,SP.POP.TOTL,Health: Population: Structure,"Population, total",None
608,South Africa,South Africa,Republic of South Africa,ZA,South African rand,Sub-Saharan Africa,Upper middle income,ZAF,SP.POP.GROW,Health: Population: Dynamics,Population growth (annual %),Annual population growth rate. Population is b...
609,Zambia,Zambia,Republic of Zambia,ZM,New Zambian kwacha,Sub-Saharan Africa,Lower middle income,ZMB,SP.POP.GROW,Health: Population: Dynamics,Population growth (annual %),Annual population growth rate. Population is b...
610,Zambia,Zambia,Republic of Zambia,ZM,New Zambian kwacha,Sub-Saharan Africa,Lower middle income,ZMB,SP.POP.TOTL,Health: Population: Structure,"Population, total",None
611,Zimbabwe,Zimbabwe,Republic of Zimbabwe,ZW,U.S. dollar,Sub-Saharan Africa,Low income,ZWE,SP.POP.TOTL,Health: Population: Structure,"Population, total",None
612,Zimbabwe,Zimbabwe,Republic of Zimbabwe,ZW,U.S. dollar,Sub-Saharan Africa,Low income,ZWE,SP.POP.GROW,Health: Population: Dynamics,Population growth (annual %),Annual population growth rate. Population is b...